/**
 * Server functions for AI-visibility analysis: Share of Voice. Read-only —
 * derived entirely from existing prompt_runs data via the postgres read layer
 * plus the pure stats in `@/lib/visibility-stats`. No schema changes.
 *
 * Filters are resolved server-side (tags/search -> prompt IDs) via
 * `resolveFilteredPrompts`, and the lookback window is computed in the user's
 * timezone — the same handling as the visibility page (see issue #68), so we
 * never serialize a brand's full prompt-id list into the request URL.
 *
 * The Opportunities page is generated by an LLM and lives in `server/opportunities.ts`.
 */
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireBrandSession } from "@/lib/auth/helpers";
import { lookbackSchema } from "@/lib/lookback";
import { resolveLookbackRange } from "@/lib/timezone-utils";
import { getBrandShareOfVoice } from "@/server/analytics-core";

export interface ShareOfVoiceEntry {
	name: string;
	mentions: number;
	share: number;
	isBrand: boolean;
	/** Distinct prompts the entity appeared in. */
	prompts: number;
}

export interface ShareOfVoiceResponse {
	brandName: string;
	entries: ShareOfVoiceEntry[];
	brandShare: number | null;
	totalRuns: number;
	model: string | null;
	/** Brand share of voice over time (percentage 0..100, null on days with no runs). */
	shareTimeSeries: Array<{ date: string; share: number | null }>;
}

export const getShareOfVoiceFn = createServerFn({ method: "GET" })
	.validator(
		z.object({
			brandId: z.string(),
			lookback: lookbackSchema.default("1m"),
			model: z.string().optional(),
			tags: z.string().optional(),
			search: z.string().optional(),
			timezone: z.string().default("UTC"),
		}),
	)
	.handler(async ({ data }): Promise<ShareOfVoiceResponse> => {
		await requireBrandSession(data.brandId);

		const { timezone, fromDateStr, toDateStr } = resolveLookbackRange(data.lookback, data.timezone);
		const result = await getBrandShareOfVoice(
			data.brandId,
			{ from: fromDateStr, to: toDateStr, timezone },
			{ model: data.model, tags: data.tags, search: data.search },
		);

		return {
			brandName: result.brandName,
			// Exact ratios, not percentages: the leaderboard, donut, and trend each
			// round the same ratio once, so they can never read a point apart.
			brandShare: result.brandShare,
			totalRuns: result.totalRuns,
			model: data.model ?? null,
			// The trend is the one figure this response carries as a percentage;
			// `brandShare` and `entries` stay ratios because the leaderboard, donut,
			// and headline each round the same ratio once at the point of display.
			shareTimeSeries: result.series.map((point) => ({
				...point,
				share: point.share === null ? null : Math.round(point.share * 100),
			})),
			entries: result.entries,
		};
	});
