/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnswerEngineOptimizationRouteImport } from './routes/answer-engine-optimization'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GenerativeEngineOptimizationRouteImport } from './routes/generative-engine-optimization'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OffSiteAeoRouteImport } from './routes/off-site-aeo'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RepoActivityDotsvgRouteImport } from './routes/repo-activity[.]svg'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as DotwellKnownAiCatalogDotjsonRouteImport } from './routes/[.]well-known/ai-catalog[.]json'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownArdDotjsonRouteImport } from './routes/[.]well-known/ard[.]json'
import { Route as AeoForIndexRouteImport } from './routes/aeo-for/index'
import { Route as AeoForSlugRouteImport } from './routes/aeo-for/$slug'
import { Route as AiSearchIndexRouteImport } from './routes/ai-search/index'
import { Route as AiSearchSlugRouteImport } from './routes/ai-search/$slug'
import { Route as AiVisibilityToolsIndexRouteImport } from './routes/ai-visibility-tools/index'
import { Route as AiVisibilityToolsSlugRouteImport } from './routes/ai-visibility-tools/$slug'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog/rss[.]xml'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as GlossarySlugRouteImport } from './routes/glossary/$slug'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalSplatRouteImport } from './routes/legal/$'
import { Route as OgStatusDotpngRouteImport } from './routes/og/status[.]png'
import { Route as DotwellKnownAgentSkillsSplatRouteImport } from './routes/[.]well-known/agent-skills/$'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known/agent-skills/index[.]json'
import { Route as AiVisibilityToolsAlternativesIndexRouteImport } from './routes/ai-visibility-tools/alternatives/index'
import { Route as AiVisibilityToolsAlternativesSlugRouteImport } from './routes/ai-visibility-tools/alternatives/$slug'
import { Route as AiVisibilityToolsCategoryIndexRouteImport } from './routes/ai-visibility-tools/category/index'
import { Route as AiVisibilityToolsCategorySlugRouteImport } from './routes/ai-visibility-tools/category/$slug'
import { Route as AiVisibilityToolsCategoryOpenSourceRouteImport } from './routes/ai-visibility-tools/category/open-source'
import { Route as AiVisibilityToolsCompareIndexRouteImport } from './routes/ai-visibility-tools/compare/index'
import { Route as AiVisibilityToolsCompareSlugRouteImport } from './routes/ai-visibility-tools/compare/$slug'
import { Route as AiVisibilityToolsFeaturesIndexRouteImport } from './routes/ai-visibility-tools/features/index'
import { Route as AiVisibilityToolsFeaturesSlugRouteImport } from './routes/ai-visibility-tools/features/$slug'
import { Route as ApiRepoActivityRefreshRouteImport } from './routes/api/repo-activity/refresh'
import { Route as LlmsDotmdxBlogSplatRouteImport } from './routes/llms[.]mdx.blog.$'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'
import { Route as ApiPlausibleEventIndexRouteImport } from './routes/api/plausible/event/index'
import { Route as ApiPlausibleJsScriptIndexRouteImport } from './routes/api/plausible/js/script/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerEngineOptimizationRoute =
  AnswerEngineOptimizationRouteImport.update({
    id: '/answer-engine-optimization',
    path: '/answer-engine-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerativeEngineOptimizationRoute =
  GenerativeEngineOptimizationRouteImport.update({
    id: '/generative-engine-optimization',
    path: '/generative-engine-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OffSiteAeoRoute = OffSiteAeoRouteImport.update({
  id: '/off-site-aeo',
  path: '/off-site-aeo',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoActivityDotsvgRoute = RepoActivityDotsvgRouteImport.update({
  id: '/repo-activity.svg',
  path: '/repo-activity.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAiCatalogDotjsonRoute =
  DotwellKnownAiCatalogDotjsonRouteImport.update({
    id: '/.well-known/ai-catalog.json',
    path: '/.well-known/ai-catalog.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownArdDotjsonRoute = DotwellKnownArdDotjsonRouteImport.update({
  id: '/.well-known/ard.json',
  path: '/.well-known/ard.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoForIndexRoute = AeoForIndexRouteImport.update({
  id: '/aeo-for/',
  path: '/aeo-for/',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoForSlugRoute = AeoForSlugRouteImport.update({
  id: '/aeo-for/$slug',
  path: '/aeo-for/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchIndexRoute = AiSearchIndexRouteImport.update({
  id: '/ai-search/',
  path: '/ai-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchSlugRoute = AiSearchSlugRouteImport.update({
  id: '/ai-search/$slug',
  path: '/ai-search/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityToolsIndexRoute = AiVisibilityToolsIndexRouteImport.update({
  id: '/ai-visibility-tools/',
  path: '/ai-visibility-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityToolsSlugRoute = AiVisibilityToolsSlugRouteImport.update({
  id: '/ai-visibility-tools/$slug',
  path: '/ai-visibility-tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarySlugRoute = GlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSplatRoute = LegalSplatRouteImport.update({
  id: '/legal/$',
  path: '/legal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgStatusDotpngRoute = OgStatusDotpngRouteImport.update({
  id: '/og/status.png',
  path: '/og/status.png',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentSkillsSplatRoute =
  DotwellKnownAgentSkillsSplatRouteImport.update({
    id: '/.well-known/agent-skills/$',
    path: '/.well-known/agent-skills/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsAlternativesIndexRoute =
  AiVisibilityToolsAlternativesIndexRouteImport.update({
    id: '/ai-visibility-tools/alternatives/',
    path: '/ai-visibility-tools/alternatives/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsAlternativesSlugRoute =
  AiVisibilityToolsAlternativesSlugRouteImport.update({
    id: '/ai-visibility-tools/alternatives/$slug',
    path: '/ai-visibility-tools/alternatives/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCategoryIndexRoute =
  AiVisibilityToolsCategoryIndexRouteImport.update({
    id: '/ai-visibility-tools/category/',
    path: '/ai-visibility-tools/category/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCategorySlugRoute =
  AiVisibilityToolsCategorySlugRouteImport.update({
    id: '/ai-visibility-tools/category/$slug',
    path: '/ai-visibility-tools/category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCategoryOpenSourceRoute =
  AiVisibilityToolsCategoryOpenSourceRouteImport.update({
    id: '/ai-visibility-tools/category/open-source',
    path: '/ai-visibility-tools/category/open-source',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCompareIndexRoute =
  AiVisibilityToolsCompareIndexRouteImport.update({
    id: '/ai-visibility-tools/compare/',
    path: '/ai-visibility-tools/compare/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsCompareSlugRoute =
  AiVisibilityToolsCompareSlugRouteImport.update({
    id: '/ai-visibility-tools/compare/$slug',
    path: '/ai-visibility-tools/compare/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsFeaturesIndexRoute =
  AiVisibilityToolsFeaturesIndexRouteImport.update({
    id: '/ai-visibility-tools/features/',
    path: '/ai-visibility-tools/features/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVisibilityToolsFeaturesSlugRoute =
  AiVisibilityToolsFeaturesSlugRouteImport.update({
    id: '/ai-visibility-tools/features/$slug',
    path: '/ai-visibility-tools/features/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRepoActivityRefreshRoute = ApiRepoActivityRefreshRouteImport.update({
  id: '/api/repo-activity/refresh',
  path: '/api/repo-activity/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxBlogSplatRoute = LlmsDotmdxBlogSplatRouteImport.update({
  id: '/llms.mdx/blog/$',
  path: '/llms.mdx/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlausibleEventIndexRoute = ApiPlausibleEventIndexRouteImport.update({
  id: '/api/plausible/event/',
  path: '/api/plausible/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlausibleJsScriptIndexRoute =
  ApiPlausibleJsScriptIndexRouteImport.update({
    id: '/api/plausible/js/script/',
    path: '/api/plausible/js/script/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer-engine-optimization': typeof AnswerEngineOptimizationRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/generative-engine-optimization': typeof GenerativeEngineOptimizationRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/pricing': typeof PricingRoute
  '/repo-activity.svg': typeof RepoActivityDotsvgRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/vision': typeof VisionRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/ard.json': typeof DotwellKnownArdDotjsonRoute
  '/aeo-for/$slug': typeof AeoForSlugRoute
  '/ai-search/$slug': typeof AiSearchSlugRoute
  '/ai-visibility-tools/$slug': typeof AiVisibilityToolsSlugRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/legal/$': typeof LegalSplatRoute
  '/og/status.png': typeof OgStatusDotpngRoute
  '/aeo-for/': typeof AeoForIndexRoute
  '/ai-search/': typeof AiSearchIndexRoute
  '/ai-visibility-tools/': typeof AiVisibilityToolsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/.well-known/agent-skills/$': typeof DotwellKnownAgentSkillsSplatRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/ai-visibility-tools/alternatives/$slug': typeof AiVisibilityToolsAlternativesSlugRoute
  '/ai-visibility-tools/category/$slug': typeof AiVisibilityToolsCategorySlugRoute
  '/ai-visibility-tools/category/open-source': typeof AiVisibilityToolsCategoryOpenSourceRoute
  '/ai-visibility-tools/compare/$slug': typeof AiVisibilityToolsCompareSlugRoute
  '/ai-visibility-tools/features/$slug': typeof AiVisibilityToolsFeaturesSlugRoute
  '/api/repo-activity/refresh': typeof ApiRepoActivityRefreshRoute
  '/llms.mdx/blog/$': typeof LlmsDotmdxBlogSplatRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/ai-visibility-tools/alternatives/': typeof AiVisibilityToolsAlternativesIndexRoute
  '/ai-visibility-tools/category/': typeof AiVisibilityToolsCategoryIndexRoute
  '/ai-visibility-tools/compare/': typeof AiVisibilityToolsCompareIndexRoute
  '/ai-visibility-tools/features/': typeof AiVisibilityToolsFeaturesIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer-engine-optimization': typeof AnswerEngineOptimizationRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/generative-engine-optimization': typeof GenerativeEngineOptimizationRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/pricing': typeof PricingRoute
  '/repo-activity.svg': typeof RepoActivityDotsvgRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/vision': typeof VisionRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/ard.json': typeof DotwellKnownArdDotjsonRoute
  '/aeo-for/$slug': typeof AeoForSlugRoute
  '/ai-search/$slug': typeof AiSearchSlugRoute
  '/ai-visibility-tools/$slug': typeof AiVisibilityToolsSlugRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/legal/$': typeof LegalSplatRoute
  '/og/status.png': typeof OgStatusDotpngRoute
  '/aeo-for': typeof AeoForIndexRoute
  '/ai-search': typeof AiSearchIndexRoute
  '/ai-visibility-tools': typeof AiVisibilityToolsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/legal': typeof LegalIndexRoute
  '/.well-known/agent-skills/$': typeof DotwellKnownAgentSkillsSplatRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/ai-visibility-tools/alternatives/$slug': typeof AiVisibilityToolsAlternativesSlugRoute
  '/ai-visibility-tools/category/$slug': typeof AiVisibilityToolsCategorySlugRoute
  '/ai-visibility-tools/category/open-source': typeof AiVisibilityToolsCategoryOpenSourceRoute
  '/ai-visibility-tools/compare/$slug': typeof AiVisibilityToolsCompareSlugRoute
  '/ai-visibility-tools/features/$slug': typeof AiVisibilityToolsFeaturesSlugRoute
  '/api/repo-activity/refresh': typeof ApiRepoActivityRefreshRoute
  '/llms.mdx/blog/$': typeof LlmsDotmdxBlogSplatRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/ai-visibility-tools/alternatives': typeof AiVisibilityToolsAlternativesIndexRoute
  '/ai-visibility-tools/category': typeof AiVisibilityToolsCategoryIndexRoute
  '/ai-visibility-tools/compare': typeof AiVisibilityToolsCompareIndexRoute
  '/ai-visibility-tools/features': typeof AiVisibilityToolsFeaturesIndexRoute
  '/api/plausible/event': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer-engine-optimization': typeof AnswerEngineOptimizationRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/features': typeof FeaturesRoute
  '/generative-engine-optimization': typeof GenerativeEngineOptimizationRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/off-site-aeo': typeof OffSiteAeoRoute
  '/og.png': typeof OgDotpngRoute
  '/pricing': typeof PricingRoute
  '/repo-activity.svg': typeof RepoActivityDotsvgRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/vision': typeof VisionRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/ard.json': typeof DotwellKnownArdDotjsonRoute
  '/aeo-for/$slug': typeof AeoForSlugRoute
  '/ai-search/$slug': typeof AiSearchSlugRoute
  '/ai-visibility-tools/$slug': typeof AiVisibilityToolsSlugRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/docs/$': typeof DocsSplatRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/legal/$': typeof LegalSplatRoute
  '/og/status.png': typeof OgStatusDotpngRoute
  '/aeo-for/': typeof AeoForIndexRoute
  '/ai-search/': typeof AiSearchIndexRoute
  '/ai-visibility-tools/': typeof AiVisibilityToolsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/.well-known/agent-skills/$': typeof DotwellKnownAgentSkillsSplatRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/ai-visibility-tools/alternatives/$slug': typeof AiVisibilityToolsAlternativesSlugRoute
  '/ai-visibility-tools/category/$slug': typeof AiVisibilityToolsCategorySlugRoute
  '/ai-visibility-tools/category/open-source': typeof AiVisibilityToolsCategoryOpenSourceRoute
  '/ai-visibility-tools/compare/$slug': typeof AiVisibilityToolsCompareSlugRoute
  '/ai-visibility-tools/features/$slug': typeof AiVisibilityToolsFeaturesSlugRoute
  '/api/repo-activity/refresh': typeof ApiRepoActivityRefreshRoute
  '/llms.mdx/blog/$': typeof LlmsDotmdxBlogSplatRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/ai-visibility-tools/alternatives/': typeof AiVisibilityToolsAlternativesIndexRoute
  '/ai-visibility-tools/category/': typeof AiVisibilityToolsCategoryIndexRoute
  '/ai-visibility-tools/compare/': typeof AiVisibilityToolsCompareIndexRoute
  '/ai-visibility-tools/features/': typeof AiVisibilityToolsFeaturesIndexRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answer-engine-optimization'
    | '/brand'
    | '/changelog'
    | '/features'
    | '/generative-engine-optimization'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/off-site-aeo'
    | '/og.png'
    | '/pricing'
    | '/repo-activity.svg'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/statistics'
    | '/status'
    | '/support'
    | '/vision'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/api-catalog'
    | '/.well-known/ard.json'
    | '/aeo-for/$slug'
    | '/ai-search/$slug'
    | '/ai-visibility-tools/$slug'
    | '/api/openapi.json'
    | '/api/search'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/docs/$'
    | '/glossary/$slug'
    | '/legal/$'
    | '/og/status.png'
    | '/aeo-for/'
    | '/ai-search/'
    | '/ai-visibility-tools/'
    | '/blog/'
    | '/docs/'
    | '/glossary/'
    | '/legal/'
    | '/.well-known/agent-skills/$'
    | '/.well-known/agent-skills/index.json'
    | '/ai-visibility-tools/alternatives/$slug'
    | '/ai-visibility-tools/category/$slug'
    | '/ai-visibility-tools/category/open-source'
    | '/ai-visibility-tools/compare/$slug'
    | '/ai-visibility-tools/features/$slug'
    | '/api/repo-activity/refresh'
    | '/llms.mdx/blog/$'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
    | '/ai-visibility-tools/alternatives/'
    | '/ai-visibility-tools/category/'
    | '/ai-visibility-tools/compare/'
    | '/ai-visibility-tools/features/'
    | '/api/plausible/event/'
    | '/api/plausible/js/script/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answer-engine-optimization'
    | '/brand'
    | '/changelog'
    | '/features'
    | '/generative-engine-optimization'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/off-site-aeo'
    | '/og.png'
    | '/pricing'
    | '/repo-activity.svg'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/statistics'
    | '/status'
    | '/support'
    | '/vision'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/api-catalog'
    | '/.well-known/ard.json'
    | '/aeo-for/$slug'
    | '/ai-search/$slug'
    | '/ai-visibility-tools/$slug'
    | '/api/openapi.json'
    | '/api/search'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/docs/$'
    | '/glossary/$slug'
    | '/legal/$'
    | '/og/status.png'
    | '/aeo-for'
    | '/ai-search'
    | '/ai-visibility-tools'
    | '/blog'
    | '/docs'
    | '/glossary'
    | '/legal'
    | '/.well-known/agent-skills/$'
    | '/.well-known/agent-skills/index.json'
    | '/ai-visibility-tools/alternatives/$slug'
    | '/ai-visibility-tools/category/$slug'
    | '/ai-visibility-tools/category/open-source'
    | '/ai-visibility-tools/compare/$slug'
    | '/ai-visibility-tools/features/$slug'
    | '/api/repo-activity/refresh'
    | '/llms.mdx/blog/$'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
    | '/ai-visibility-tools/alternatives'
    | '/ai-visibility-tools/category'
    | '/ai-visibility-tools/compare'
    | '/ai-visibility-tools/features'
    | '/api/plausible/event'
    | '/api/plausible/js/script'
  id:
    | '__root__'
    | '/'
    | '/answer-engine-optimization'
    | '/brand'
    | '/changelog'
    | '/features'
    | '/generative-engine-optimization'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/off-site-aeo'
    | '/og.png'
    | '/pricing'
    | '/repo-activity.svg'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/statistics'
    | '/status'
    | '/support'
    | '/vision'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/api-catalog'
    | '/.well-known/ard.json'
    | '/aeo-for/$slug'
    | '/ai-search/$slug'
    | '/ai-visibility-tools/$slug'
    | '/api/openapi.json'
    | '/api/search'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/docs/$'
    | '/glossary/$slug'
    | '/legal/$'
    | '/og/status.png'
    | '/aeo-for/'
    | '/ai-search/'
    | '/ai-visibility-tools/'
    | '/blog/'
    | '/docs/'
    | '/glossary/'
    | '/legal/'
    | '/.well-known/agent-skills/$'
    | '/.well-known/agent-skills/index.json'
    | '/ai-visibility-tools/alternatives/$slug'
    | '/ai-visibility-tools/category/$slug'
    | '/ai-visibility-tools/category/open-source'
    | '/ai-visibility-tools/compare/$slug'
    | '/ai-visibility-tools/features/$slug'
    | '/api/repo-activity/refresh'
    | '/llms.mdx/blog/$'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
    | '/ai-visibility-tools/alternatives/'
    | '/ai-visibility-tools/category/'
    | '/ai-visibility-tools/compare/'
    | '/ai-visibility-tools/features/'
    | '/api/plausible/event/'
    | '/api/plausible/js/script/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerEngineOptimizationRoute: typeof AnswerEngineOptimizationRoute
  BrandRoute: typeof BrandRoute
  ChangelogRoute: typeof ChangelogRoute
  FeaturesRoute: typeof FeaturesRoute
  GenerativeEngineOptimizationRoute: typeof GenerativeEngineOptimizationRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OffSiteAeoRoute: typeof OffSiteAeoRoute
  OgDotpngRoute: typeof OgDotpngRoute
  PricingRoute: typeof PricingRoute
  RepoActivityDotsvgRoute: typeof RepoActivityDotsvgRoute
  RoadmapRoute: typeof RoadmapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatisticsRoute: typeof StatisticsRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  VisionRoute: typeof VisionRoute
  DotwellKnownAiCatalogDotjsonRoute: typeof DotwellKnownAiCatalogDotjsonRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownArdDotjsonRoute: typeof DotwellKnownArdDotjsonRoute
  AeoForSlugRoute: typeof AeoForSlugRoute
  AiSearchSlugRoute: typeof AiSearchSlugRoute
  AiVisibilityToolsSlugRoute: typeof AiVisibilityToolsSlugRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSplatRoute: typeof BlogSplatRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  DocsSplatRoute: typeof DocsSplatRoute
  GlossarySlugRoute: typeof GlossarySlugRoute
  LegalSplatRoute: typeof LegalSplatRoute
  OgStatusDotpngRoute: typeof OgStatusDotpngRoute
  AeoForIndexRoute: typeof AeoForIndexRoute
  AiSearchIndexRoute: typeof AiSearchIndexRoute
  AiVisibilityToolsIndexRoute: typeof AiVisibilityToolsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  DotwellKnownAgentSkillsSplatRoute: typeof DotwellKnownAgentSkillsSplatRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  AiVisibilityToolsAlternativesSlugRoute: typeof AiVisibilityToolsAlternativesSlugRoute
  AiVisibilityToolsCategorySlugRoute: typeof AiVisibilityToolsCategorySlugRoute
  AiVisibilityToolsCategoryOpenSourceRoute: typeof AiVisibilityToolsCategoryOpenSourceRoute
  AiVisibilityToolsCompareSlugRoute: typeof AiVisibilityToolsCompareSlugRoute
  AiVisibilityToolsFeaturesSlugRoute: typeof AiVisibilityToolsFeaturesSlugRoute
  ApiRepoActivityRefreshRoute: typeof ApiRepoActivityRefreshRoute
  LlmsDotmdxBlogSplatRoute: typeof LlmsDotmdxBlogSplatRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
  AiVisibilityToolsAlternativesIndexRoute: typeof AiVisibilityToolsAlternativesIndexRoute
  AiVisibilityToolsCategoryIndexRoute: typeof AiVisibilityToolsCategoryIndexRoute
  AiVisibilityToolsCompareIndexRoute: typeof AiVisibilityToolsCompareIndexRoute
  AiVisibilityToolsFeaturesIndexRoute: typeof AiVisibilityToolsFeaturesIndexRoute
  ApiPlausibleEventIndexRoute: typeof ApiPlausibleEventIndexRoute
  ApiPlausibleJsScriptIndexRoute: typeof ApiPlausibleJsScriptIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-engine-optimization': {
      id: '/answer-engine-optimization'
      path: '/answer-engine-optimization'
      fullPath: '/answer-engine-optimization'
      preLoaderRoute: typeof AnswerEngineOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generative-engine-optimization': {
      id: '/generative-engine-optimization'
      path: '/generative-engine-optimization'
      fullPath: '/generative-engine-optimization'
      preLoaderRoute: typeof GenerativeEngineOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-site-aeo': {
      id: '/off-site-aeo'
      path: '/off-site-aeo'
      fullPath: '/off-site-aeo'
      preLoaderRoute: typeof OffSiteAeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-activity.svg': {
      id: '/repo-activity.svg'
      path: '/repo-activity.svg'
      fullPath: '/repo-activity.svg'
      preLoaderRoute: typeof RepoActivityDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-catalog.json': {
      id: '/.well-known/ai-catalog.json'
      path: '/.well-known/ai-catalog.json'
      fullPath: '/.well-known/ai-catalog.json'
      preLoaderRoute: typeof DotwellKnownAiCatalogDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ard.json': {
      id: '/.well-known/ard.json'
      path: '/.well-known/ard.json'
      fullPath: '/.well-known/ard.json'
      preLoaderRoute: typeof DotwellKnownArdDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-for/': {
      id: '/aeo-for/'
      path: '/aeo-for'
      fullPath: '/aeo-for/'
      preLoaderRoute: typeof AeoForIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-for/$slug': {
      id: '/aeo-for/$slug'
      path: '/aeo-for/$slug'
      fullPath: '/aeo-for/$slug'
      preLoaderRoute: typeof AeoForSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search/': {
      id: '/ai-search/'
      path: '/ai-search'
      fullPath: '/ai-search/'
      preLoaderRoute: typeof AiSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search/$slug': {
      id: '/ai-search/$slug'
      path: '/ai-search/$slug'
      fullPath: '/ai-search/$slug'
      preLoaderRoute: typeof AiSearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/': {
      id: '/ai-visibility-tools/'
      path: '/ai-visibility-tools'
      fullPath: '/ai-visibility-tools/'
      preLoaderRoute: typeof AiVisibilityToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/$slug': {
      id: '/ai-visibility-tools/$slug'
      path: '/ai-visibility-tools/$slug'
      fullPath: '/ai-visibility-tools/$slug'
      preLoaderRoute: typeof AiVisibilityToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$slug': {
      id: '/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof GlossarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$': {
      id: '/legal/$'
      path: '/legal/$'
      fullPath: '/legal/$'
      preLoaderRoute: typeof LegalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/status.png': {
      id: '/og/status.png'
      path: '/og/status.png'
      fullPath: '/og/status.png'
      preLoaderRoute: typeof OgStatusDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/$': {
      id: '/.well-known/agent-skills/$'
      path: '/.well-known/agent-skills/$'
      fullPath: '/.well-known/agent-skills/$'
      preLoaderRoute: typeof DotwellKnownAgentSkillsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/alternatives/': {
      id: '/ai-visibility-tools/alternatives/'
      path: '/ai-visibility-tools/alternatives'
      fullPath: '/ai-visibility-tools/alternatives/'
      preLoaderRoute: typeof AiVisibilityToolsAlternativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/alternatives/$slug': {
      id: '/ai-visibility-tools/alternatives/$slug'
      path: '/ai-visibility-tools/alternatives/$slug'
      fullPath: '/ai-visibility-tools/alternatives/$slug'
      preLoaderRoute: typeof AiVisibilityToolsAlternativesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/category/': {
      id: '/ai-visibility-tools/category/'
      path: '/ai-visibility-tools/category'
      fullPath: '/ai-visibility-tools/category/'
      preLoaderRoute: typeof AiVisibilityToolsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/category/$slug': {
      id: '/ai-visibility-tools/category/$slug'
      path: '/ai-visibility-tools/category/$slug'
      fullPath: '/ai-visibility-tools/category/$slug'
      preLoaderRoute: typeof AiVisibilityToolsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/category/open-source': {
      id: '/ai-visibility-tools/category/open-source'
      path: '/ai-visibility-tools/category/open-source'
      fullPath: '/ai-visibility-tools/category/open-source'
      preLoaderRoute: typeof AiVisibilityToolsCategoryOpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/compare/': {
      id: '/ai-visibility-tools/compare/'
      path: '/ai-visibility-tools/compare'
      fullPath: '/ai-visibility-tools/compare/'
      preLoaderRoute: typeof AiVisibilityToolsCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/compare/$slug': {
      id: '/ai-visibility-tools/compare/$slug'
      path: '/ai-visibility-tools/compare/$slug'
      fullPath: '/ai-visibility-tools/compare/$slug'
      preLoaderRoute: typeof AiVisibilityToolsCompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/features/': {
      id: '/ai-visibility-tools/features/'
      path: '/ai-visibility-tools/features'
      fullPath: '/ai-visibility-tools/features/'
      preLoaderRoute: typeof AiVisibilityToolsFeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility-tools/features/$slug': {
      id: '/ai-visibility-tools/features/$slug'
      path: '/ai-visibility-tools/features/$slug'
      fullPath: '/ai-visibility-tools/features/$slug'
      preLoaderRoute: typeof AiVisibilityToolsFeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repo-activity/refresh': {
      id: '/api/repo-activity/refresh'
      path: '/api/repo-activity/refresh'
      fullPath: '/api/repo-activity/refresh'
      preLoaderRoute: typeof ApiRepoActivityRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/blog/$': {
      id: '/llms.mdx/blog/$'
      path: '/llms.mdx/blog/$'
      fullPath: '/llms.mdx/blog/$'
      preLoaderRoute: typeof LlmsDotmdxBlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plausible/event/': {
      id: '/api/plausible/event/'
      path: '/api/plausible/event'
      fullPath: '/api/plausible/event/'
      preLoaderRoute: typeof ApiPlausibleEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plausible/js/script/': {
      id: '/api/plausible/js/script/'
      path: '/api/plausible/js/script'
      fullPath: '/api/plausible/js/script/'
      preLoaderRoute: typeof ApiPlausibleJsScriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerEngineOptimizationRoute: AnswerEngineOptimizationRoute,
  BrandRoute: BrandRoute,
  ChangelogRoute: ChangelogRoute,
  FeaturesRoute: FeaturesRoute,
  GenerativeEngineOptimizationRoute: GenerativeEngineOptimizationRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OffSiteAeoRoute: OffSiteAeoRoute,
  OgDotpngRoute: OgDotpngRoute,
  PricingRoute: PricingRoute,
  RepoActivityDotsvgRoute: RepoActivityDotsvgRoute,
  RoadmapRoute: RoadmapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatisticsRoute: StatisticsRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  VisionRoute: VisionRoute,
  DotwellKnownAiCatalogDotjsonRoute: DotwellKnownAiCatalogDotjsonRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownArdDotjsonRoute: DotwellKnownArdDotjsonRoute,
  AeoForSlugRoute: AeoForSlugRoute,
  AiSearchSlugRoute: AiSearchSlugRoute,
  AiVisibilityToolsSlugRoute: AiVisibilityToolsSlugRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSplatRoute: BlogSplatRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  DocsSplatRoute: DocsSplatRoute,
  GlossarySlugRoute: GlossarySlugRoute,
  LegalSplatRoute: LegalSplatRoute,
  OgStatusDotpngRoute: OgStatusDotpngRoute,
  AeoForIndexRoute: AeoForIndexRoute,
  AiSearchIndexRoute: AiSearchIndexRoute,
  AiVisibilityToolsIndexRoute: AiVisibilityToolsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  DotwellKnownAgentSkillsSplatRoute: DotwellKnownAgentSkillsSplatRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  AiVisibilityToolsAlternativesSlugRoute:
    AiVisibilityToolsAlternativesSlugRoute,
  AiVisibilityToolsCategorySlugRoute: AiVisibilityToolsCategorySlugRoute,
  AiVisibilityToolsCategoryOpenSourceRoute:
    AiVisibilityToolsCategoryOpenSourceRoute,
  AiVisibilityToolsCompareSlugRoute: AiVisibilityToolsCompareSlugRoute,
  AiVisibilityToolsFeaturesSlugRoute: AiVisibilityToolsFeaturesSlugRoute,
  ApiRepoActivityRefreshRoute: ApiRepoActivityRefreshRoute,
  LlmsDotmdxBlogSplatRoute: LlmsDotmdxBlogSplatRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
  AiVisibilityToolsAlternativesIndexRoute:
    AiVisibilityToolsAlternativesIndexRoute,
  AiVisibilityToolsCategoryIndexRoute: AiVisibilityToolsCategoryIndexRoute,
  AiVisibilityToolsCompareIndexRoute: AiVisibilityToolsCompareIndexRoute,
  AiVisibilityToolsFeaturesIndexRoute: AiVisibilityToolsFeaturesIndexRoute,
  ApiPlausibleEventIndexRoute: ApiPlausibleEventIndexRoute,
  ApiPlausibleJsScriptIndexRoute: ApiPlausibleJsScriptIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
