export interface TeamAuthor {
	name: string;
	role: string;
	/**
	 * Square photo under public/, e.g. "/authors/jared.png". Omit to render an
	 * initials avatar instead (no image asset required).
	 */
	avatar?: string;
	/** Optional external profile link (personal site, X, etc.). */
	url?: string;
}

/**
 * Real people at the company. A blog post's frontmatter `author` field
 * references one of these keys to render a full byline. To add yourself: add
 * an entry here and (optionally) drop a square photo at
 * apps/www/public/authors/<key>.png and set `avatar`.
 */
const teamAuthors = {
	jared: {
		name: "Jared Rhizor",
		role: "Founder",
		avatar: "/authors/jared.png",
	},
} satisfies Record<string, TeamAuthor>;

type TeamAuthorKey = keyof typeof teamAuthors;

/** Reserved frontmatter `author` value marking a post as AI-generated. */
const AI_AUTHOR = "ai";

export type ResolvedAuthor =
	| { kind: "team"; key: TeamAuthorKey; author: TeamAuthor }
	| { kind: "ai" }
	| { kind: "unknown"; name: string };

/**
 * Resolve a frontmatter `author` value:
 * - "ai" → AI-generated byline
 * - a known team key → full team byline
 * - anything else → shown as a plain name (so a typo'd key isn't mislabeled
 *   as AI-generated)
 */
export function resolveAuthor(value: string): ResolvedAuthor {
	if (value === AI_AUTHOR) return { kind: "ai" };
	if (Object.hasOwn(teamAuthors, value)) {
		const key = value as TeamAuthorKey;
		return { kind: "team", key, author: teamAuthors[key] };
	}
	return { kind: "unknown", name: value };
}

export function isAiAuthor(value: string): boolean {
	return resolveAuthor(value).kind === "ai";
}

/** Name to show in compact contexts (post lists, JSON-LD fallbacks). */
export function authorDisplayName(value: string): string {
	const resolved = resolveAuthor(value);
	if (resolved.kind === "team") return resolved.author.name;
	if (resolved.kind === "unknown") return resolved.name;
	return "Elmo";
}
