/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthedChoosePlanRouteImport } from './routes/_authed/choose-plan'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthAuthorizeRouteImport } from './routes/auth/authorize'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as DotwellKnownOauthAuthorizationServerIndexRouteImport } from './routes/[.]well-known/oauth-authorization-server/index'
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from './routes/[.]well-known/oauth-authorization-server/$'
import { Route as DotwellKnownOauthProtectedResourceIndexRouteImport } from './routes/[.]well-known/oauth-protected-resource/index'
import { Route as DotwellKnownOauthProtectedResourceSplatRouteImport } from './routes/[.]well-known/oauth-protected-resource/$'
import { Route as AuthedAcceptInvitationInvitationIdRouteImport } from './routes/_authed/accept-invitation/$invitationId'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminToolsRouteImport } from './routes/_authed/admin/tools'
import { Route as AuthedAdminWorkflowsRouteImport } from './routes/_authed/admin/workflows'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'
import { Route as AuthedAppNewRouteImport } from './routes/_authed/app/new'
import { Route as AuthedReportsIndexRouteImport } from './routes/_authed/reports/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiManifestIndexRouteImport } from './routes/api/manifest/index'
import { Route as ApiMcpSplatRouteImport } from './routes/api/mcp/$'
import { Route as ApiOgIndexRouteImport } from './routes/api/og/index'
import { Route as ApiSetupStatusIndexRouteImport } from './routes/api/setup-status/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1ModelsRouteImport } from './routes/api/v1/models'
import { Route as AuthedAppOrgOrgRouteImport } from './routes/_authed/app/org/$org'
import { Route as AuthedReportsRenderReportIdRouteImport } from './routes/_authed/reports/render/$reportId'
import { Route as ApiPlausibleEventIndexRouteImport } from './routes/api/plausible/event/index'
import { Route as ApiV1BrandsIndexRouteImport } from './routes/api/v1/brands/index'
import { Route as ApiV1BrandsBrandIdRouteImport } from './routes/api/v1/brands/$brandId'
import { Route as ApiV1CompetitorsIndexRouteImport } from './routes/api/v1/competitors/index'
import { Route as ApiV1CompetitorsCompetitorIdRouteImport } from './routes/api/v1/competitors/$competitorId'
import { Route as ApiV1DocsIndexRouteImport } from './routes/api/v1/docs/index'
import { Route as ApiV1OrganizationsIndexRouteImport } from './routes/api/v1/organizations/index'
import { Route as ApiV1OrganizationsOrganizationIdRouteImport } from './routes/api/v1/organizations/$organizationId'
import { Route as ApiV1PromptsIndexRouteImport } from './routes/api/v1/prompts/index'
import { Route as ApiV1PromptsPromptIdRouteImport } from './routes/api/v1/prompts/$promptId'
import { Route as ApiV1ReportsIndexRouteImport } from './routes/api/v1/reports/index'
import { Route as ApiV1ReportsReportIdRouteImport } from './routes/api/v1/reports/$reportId'
import { Route as ApiV1ToolsAnalyzeRouteImport } from './routes/api/v1/tools/analyze'
import { Route as AuthedAppOrgOrgIndexRouteImport } from './routes/_authed/app/org/$org/index'
import { Route as AuthedAppOrgOrgNewRouteImport } from './routes/_authed/app/org/$org/new'
import { Route as AuthedAppOrgOrgSettingsRouteImport } from './routes/_authed/app/org/$org/settings'
import { Route as ApiPlausibleJsScriptIndexRouteImport } from './routes/api/plausible/js/script/index'
import { Route as ApiV1BrandsBrandIdAnalyticsRouteImport } from './routes/api/v1/brands/$brandId/analytics'
import { Route as ApiV1BrandsBrandIdOpportunitiesRouteImport } from './routes/api/v1/brands/$brandId/opportunities'
import { Route as ApiV1BrandsBrandIdPromptPerformanceRouteImport } from './routes/api/v1/brands/$brandId/prompt-performance'
import { Route as ApiV1BrandsBrandIdQueryFanoutRouteImport } from './routes/api/v1/brands/$brandId/query-fanout'
import { Route as ApiV1OrganizationsOrganizationIdBillingRouteImport } from './routes/api/v1/organizations/$organizationId/billing'
import { Route as ApiV1PromptsPromptIdSnapshotRouteImport } from './routes/api/v1/prompts/$promptId/snapshot'
import { Route as AuthedAppOrgOrgBrandBrandRouteImport } from './routes/_authed/app/org/$org/brand/$brand'
import { Route as AuthedAppOrgOrgSettingsIndexRouteImport } from './routes/_authed/app/org/$org/settings/index'
import { Route as AuthedAppOrgOrgSettingsApiRouteImport } from './routes/_authed/app/org/$org/settings/api'
import { Route as AuthedAppOrgOrgSettingsApiKeysRouteImport } from './routes/_authed/app/org/$org/settings/api-keys'
import { Route as AuthedAppOrgOrgSettingsBillingRouteImport } from './routes/_authed/app/org/$org/settings/billing'
import { Route as AuthedAppOrgOrgSettingsBrandsRouteImport } from './routes/_authed/app/org/$org/settings/brands'
import { Route as AuthedAppOrgOrgSettingsMcpRouteImport } from './routes/_authed/app/org/$org/settings/mcp'
import { Route as AuthedAppOrgOrgSettingsMembersRouteImport } from './routes/_authed/app/org/$org/settings/members'
import { Route as ApiV1BrandsBrandIdCitationsDomainsRouteImport } from './routes/api/v1/brands/$brandId/citations/domains'
import { Route as ApiV1BrandsBrandIdCitationsUrlsRouteImport } from './routes/api/v1/brands/$brandId/citations/urls'
import { Route as ApiV1BrandsBrandIdTagsIndexRouteImport } from './routes/api/v1/brands/$brandId/tags/index'
import { Route as ApiV1PromptsPromptIdRunsIndexRouteImport } from './routes/api/v1/prompts/$promptId/runs/index'
import { Route as ApiV1PromptsPromptIdRunsRunIdRouteImport } from './routes/api/v1/prompts/$promptId/runs/$runId'
import { Route as AuthedAppOrgOrgBrandBrandIndexRouteImport } from './routes/_authed/app/org/$org/brand/$brand/index'
import { Route as AuthedAppOrgOrgBrandBrandSplatRouteImport } from './routes/_authed/app/org/$org/brand/$brand/$'
import { Route as AuthedAppOrgOrgBrandBrandCitationsRouteImport } from './routes/_authed/app/org/$org/brand/$brand/citations'
import { Route as AuthedAppOrgOrgBrandBrandOpportunitiesRouteImport } from './routes/_authed/app/org/$org/brand/$brand/opportunities'
import { Route as AuthedAppOrgOrgBrandBrandQueryFanOutRouteImport } from './routes/_authed/app/org/$org/brand/$brand/query-fan-out'
import { Route as AuthedAppOrgOrgBrandBrandShareOfVoiceRouteImport } from './routes/_authed/app/org/$org/brand/$brand/share-of-voice'
import { Route as AuthedAppOrgOrgBrandBrandVisibilityRouteImport } from './routes/_authed/app/org/$org/brand/$brand/visibility'
import { Route as AuthedAppOrgOrgBrandBrandPromptsIndexRouteImport } from './routes/_authed/app/org/$org/brand/$brand/prompts/index'
import { Route as AuthedAppOrgOrgBrandBrandPromptsPromptIdRouteImport } from './routes/_authed/app/org/$org/brand/$brand/prompts/$promptId'
import { Route as AuthedAppOrgOrgBrandBrandPromptsEditRouteImport } from './routes/_authed/app/org/$org/brand/$brand/prompts/edit'
import { Route as AuthedAppOrgOrgBrandBrandSettingsIndexRouteImport } from './routes/_authed/app/org/$org/brand/$brand/settings/index'
import { Route as AuthedAppOrgOrgBrandBrandSettingsBrandRouteImport } from './routes/_authed/app/org/$org/brand/$brand/settings/brand'
import { Route as AuthedAppOrgOrgBrandBrandSettingsCompetitorsRouteImport } from './routes/_authed/app/org/$org/brand/$brand/settings/competitors'
import { Route as AuthedAppOrgOrgBrandBrandSettingsLlmsRouteImport } from './routes/_authed/app/org/$org/brand/$brand/settings/llms'
import { Route as AuthedAppOrgOrgBrandBrandSettingsPromptsRouteImport } from './routes/_authed/app/org/$org/brand/$brand/settings/prompts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChoosePlanRoute = AuthedChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthAuthorizeRoute = AuthAuthorizeRouteImport.update({
  id: '/auth/authorize',
  path: '/auth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerIndexRoute =
  DotwellKnownOauthAuthorizationServerIndexRouteImport.update({
    id: '/.well-known/oauth-authorization-server/',
    path: '/.well-known/oauth-authorization-server/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: '/.well-known/oauth-authorization-server/$',
    path: '/.well-known/oauth-authorization-server/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceIndexRoute =
  DotwellKnownOauthProtectedResourceIndexRouteImport.update({
    id: '/.well-known/oauth-protected-resource/',
    path: '/.well-known/oauth-protected-resource/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceSplatRoute =
  DotwellKnownOauthProtectedResourceSplatRouteImport.update({
    id: '/.well-known/oauth-protected-resource/$',
    path: '/.well-known/oauth-protected-resource/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedAcceptInvitationInvitationIdRoute =
  AuthedAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminToolsRoute = AuthedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminWorkflowsRoute = AuthedAdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppNewRoute = AuthedAppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedReportsIndexRoute = AuthedReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedReportsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestIndexRoute = ApiManifestIndexRouteImport.update({
  id: '/api/manifest/',
  path: '/api/manifest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSplatRoute = ApiMcpSplatRouteImport.update({
  id: '/api/mcp/$',
  path: '/api/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupStatusIndexRoute = ApiSetupStatusIndexRouteImport.update({
  id: '/api/setup-status/',
  path: '/api/setup-status/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ModelsRoute = ApiV1ModelsRouteImport.update({
  id: '/api/v1/models',
  path: '/api/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppOrgOrgRoute = AuthedAppOrgOrgRouteImport.update({
  id: '/org/$org',
  path: '/org/$org',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedReportsRenderReportIdRoute =
  AuthedReportsRenderReportIdRouteImport.update({
    id: '/render/$reportId',
    path: '/render/$reportId',
    getParentRoute: () => AuthedReportsRoute,
  } as any)
const ApiPlausibleEventIndexRoute = ApiPlausibleEventIndexRouteImport.update({
  id: '/api/plausible/event/',
  path: '/api/plausible/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrandsIndexRoute = ApiV1BrandsIndexRouteImport.update({
  id: '/api/v1/brands/',
  path: '/api/v1/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrandsBrandIdRoute = ApiV1BrandsBrandIdRouteImport.update({
  id: '/api/v1/brands/$brandId',
  path: '/api/v1/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompetitorsIndexRoute = ApiV1CompetitorsIndexRouteImport.update({
  id: '/api/v1/competitors/',
  path: '/api/v1/competitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompetitorsCompetitorIdRoute =
  ApiV1CompetitorsCompetitorIdRouteImport.update({
    id: '/api/v1/competitors/$competitorId',
    path: '/api/v1/competitors/$competitorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DocsIndexRoute = ApiV1DocsIndexRouteImport.update({
  id: '/api/v1/docs/',
  path: '/api/v1/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrganizationsIndexRoute = ApiV1OrganizationsIndexRouteImport.update({
  id: '/api/v1/organizations/',
  path: '/api/v1/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrganizationsOrganizationIdRoute =
  ApiV1OrganizationsOrganizationIdRouteImport.update({
    id: '/api/v1/organizations/$organizationId',
    path: '/api/v1/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1PromptsIndexRoute = ApiV1PromptsIndexRouteImport.update({
  id: '/api/v1/prompts/',
  path: '/api/v1/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PromptsPromptIdRoute = ApiV1PromptsPromptIdRouteImport.update({
  id: '/api/v1/prompts/$promptId',
  path: '/api/v1/prompts/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsIndexRoute = ApiV1ReportsIndexRouteImport.update({
  id: '/api/v1/reports/',
  path: '/api/v1/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsReportIdRoute = ApiV1ReportsReportIdRouteImport.update({
  id: '/api/v1/reports/$reportId',
  path: '/api/v1/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ToolsAnalyzeRoute = ApiV1ToolsAnalyzeRouteImport.update({
  id: '/api/v1/tools/analyze',
  path: '/api/v1/tools/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppOrgOrgIndexRoute = AuthedAppOrgOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppOrgOrgRoute,
} as any)
const AuthedAppOrgOrgNewRoute = AuthedAppOrgOrgNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedAppOrgOrgRoute,
} as any)
const AuthedAppOrgOrgSettingsRoute = AuthedAppOrgOrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppOrgOrgRoute,
} as any)
const ApiPlausibleJsScriptIndexRoute =
  ApiPlausibleJsScriptIndexRouteImport.update({
    id: '/api/plausible/js/script/',
    path: '/api/plausible/js/script/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1BrandsBrandIdAnalyticsRoute =
  ApiV1BrandsBrandIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1BrandsBrandIdOpportunitiesRoute =
  ApiV1BrandsBrandIdOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1BrandsBrandIdPromptPerformanceRoute =
  ApiV1BrandsBrandIdPromptPerformanceRouteImport.update({
    id: '/prompt-performance',
    path: '/prompt-performance',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1BrandsBrandIdQueryFanoutRoute =
  ApiV1BrandsBrandIdQueryFanoutRouteImport.update({
    id: '/query-fanout',
    path: '/query-fanout',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1OrganizationsOrganizationIdBillingRoute =
  ApiV1OrganizationsOrganizationIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ApiV1OrganizationsOrganizationIdRoute,
  } as any)
const ApiV1PromptsPromptIdSnapshotRoute =
  ApiV1PromptsPromptIdSnapshotRouteImport.update({
    id: '/snapshot',
    path: '/snapshot',
    getParentRoute: () => ApiV1PromptsPromptIdRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandRoute =
  AuthedAppOrgOrgBrandBrandRouteImport.update({
    id: '/brand/$brand',
    path: '/brand/$brand',
    getParentRoute: () => AuthedAppOrgOrgRoute,
  } as any)
const AuthedAppOrgOrgSettingsIndexRoute =
  AuthedAppOrgOrgSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const AuthedAppOrgOrgSettingsApiRoute =
  AuthedAppOrgOrgSettingsApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const AuthedAppOrgOrgSettingsApiKeysRoute =
  AuthedAppOrgOrgSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const AuthedAppOrgOrgSettingsBillingRoute =
  AuthedAppOrgOrgSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const AuthedAppOrgOrgSettingsBrandsRoute =
  AuthedAppOrgOrgSettingsBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const AuthedAppOrgOrgSettingsMcpRoute =
  AuthedAppOrgOrgSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const AuthedAppOrgOrgSettingsMembersRoute =
  AuthedAppOrgOrgSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedAppOrgOrgSettingsRoute,
  } as any)
const ApiV1BrandsBrandIdCitationsDomainsRoute =
  ApiV1BrandsBrandIdCitationsDomainsRouteImport.update({
    id: '/citations/domains',
    path: '/citations/domains',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1BrandsBrandIdCitationsUrlsRoute =
  ApiV1BrandsBrandIdCitationsUrlsRouteImport.update({
    id: '/citations/urls',
    path: '/citations/urls',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1BrandsBrandIdTagsIndexRoute =
  ApiV1BrandsBrandIdTagsIndexRouteImport.update({
    id: '/tags/',
    path: '/tags/',
    getParentRoute: () => ApiV1BrandsBrandIdRoute,
  } as any)
const ApiV1PromptsPromptIdRunsIndexRoute =
  ApiV1PromptsPromptIdRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => ApiV1PromptsPromptIdRoute,
  } as any)
const ApiV1PromptsPromptIdRunsRunIdRoute =
  ApiV1PromptsPromptIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ApiV1PromptsPromptIdRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandIndexRoute =
  AuthedAppOrgOrgBrandBrandIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandSplatRoute =
  AuthedAppOrgOrgBrandBrandSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandCitationsRoute =
  AuthedAppOrgOrgBrandBrandCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandOpportunitiesRoute =
  AuthedAppOrgOrgBrandBrandOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandQueryFanOutRoute =
  AuthedAppOrgOrgBrandBrandQueryFanOutRouteImport.update({
    id: '/query-fan-out',
    path: '/query-fan-out',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandShareOfVoiceRoute =
  AuthedAppOrgOrgBrandBrandShareOfVoiceRouteImport.update({
    id: '/share-of-voice',
    path: '/share-of-voice',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandVisibilityRoute =
  AuthedAppOrgOrgBrandBrandVisibilityRouteImport.update({
    id: '/visibility',
    path: '/visibility',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandPromptsIndexRoute =
  AuthedAppOrgOrgBrandBrandPromptsIndexRouteImport.update({
    id: '/prompts/',
    path: '/prompts/',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute =
  AuthedAppOrgOrgBrandBrandPromptsPromptIdRouteImport.update({
    id: '/prompts/$promptId',
    path: '/prompts/$promptId',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandPromptsEditRoute =
  AuthedAppOrgOrgBrandBrandPromptsEditRouteImport.update({
    id: '/prompts/edit',
    path: '/prompts/edit',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandSettingsIndexRoute =
  AuthedAppOrgOrgBrandBrandSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandSettingsBrandRoute =
  AuthedAppOrgOrgBrandBrandSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute =
  AuthedAppOrgOrgBrandBrandSettingsCompetitorsRouteImport.update({
    id: '/settings/competitors',
    path: '/settings/competitors',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandSettingsLlmsRoute =
  AuthedAppOrgOrgBrandBrandSettingsLlmsRouteImport.update({
    id: '/settings/llms',
    path: '/settings/llms',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)
const AuthedAppOrgOrgBrandBrandSettingsPromptsRoute =
  AuthedAppOrgOrgBrandBrandSettingsPromptsRouteImport.update({
    id: '/settings/prompts',
    path: '/settings/prompts',
    getParentRoute: () => AuthedAppOrgOrgBrandBrandRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/app': typeof AuthedAppRouteWithChildren
  '/choose-plan': typeof AuthedChoosePlanRoute
  '/reports': typeof AuthedReportsRouteWithChildren
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/accept-invitation/$invitationId': typeof AuthedAcceptInvitationInvitationIdRoute
  '/admin/tools': typeof AuthedAdminToolsRoute
  '/admin/workflows': typeof AuthedAdminWorkflowsRoute
  '/app/new': typeof AuthedAppNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/.well-known/oauth-authorization-server/': typeof DotwellKnownOauthAuthorizationServerIndexRoute
  '/.well-known/oauth-protected-resource/': typeof DotwellKnownOauthProtectedResourceIndexRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/app/': typeof AuthedAppIndexRoute
  '/reports/': typeof AuthedReportsIndexRoute
  '/api/manifest/': typeof ApiManifestIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/api/setup-status/': typeof ApiSetupStatusIndexRoute
  '/app/org/$org': typeof AuthedAppOrgOrgRouteWithChildren
  '/reports/render/$reportId': typeof AuthedReportsRenderReportIdRoute
  '/api/v1/brands/$brandId': typeof ApiV1BrandsBrandIdRouteWithChildren
  '/api/v1/competitors/$competitorId': typeof ApiV1CompetitorsCompetitorIdRoute
  '/api/v1/organizations/$organizationId': typeof ApiV1OrganizationsOrganizationIdRouteWithChildren
  '/api/v1/prompts/$promptId': typeof ApiV1PromptsPromptIdRouteWithChildren
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
  '/api/v1/tools/analyze': typeof ApiV1ToolsAnalyzeRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/v1/brands/': typeof ApiV1BrandsIndexRoute
  '/api/v1/competitors/': typeof ApiV1CompetitorsIndexRoute
  '/api/v1/docs/': typeof ApiV1DocsIndexRoute
  '/api/v1/organizations/': typeof ApiV1OrganizationsIndexRoute
  '/api/v1/prompts/': typeof ApiV1PromptsIndexRoute
  '/api/v1/reports/': typeof ApiV1ReportsIndexRoute
  '/app/org/$org/new': typeof AuthedAppOrgOrgNewRoute
  '/app/org/$org/settings': typeof AuthedAppOrgOrgSettingsRouteWithChildren
  '/api/v1/brands/$brandId/analytics': typeof ApiV1BrandsBrandIdAnalyticsRoute
  '/api/v1/brands/$brandId/opportunities': typeof ApiV1BrandsBrandIdOpportunitiesRoute
  '/api/v1/brands/$brandId/prompt-performance': typeof ApiV1BrandsBrandIdPromptPerformanceRoute
  '/api/v1/brands/$brandId/query-fanout': typeof ApiV1BrandsBrandIdQueryFanoutRoute
  '/api/v1/organizations/$organizationId/billing': typeof ApiV1OrganizationsOrganizationIdBillingRoute
  '/api/v1/prompts/$promptId/snapshot': typeof ApiV1PromptsPromptIdSnapshotRoute
  '/app/org/$org/': typeof AuthedAppOrgOrgIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
  '/app/org/$org/brand/$brand': typeof AuthedAppOrgOrgBrandBrandRouteWithChildren
  '/app/org/$org/settings/api': typeof AuthedAppOrgOrgSettingsApiRoute
  '/app/org/$org/settings/api-keys': typeof AuthedAppOrgOrgSettingsApiKeysRoute
  '/app/org/$org/settings/billing': typeof AuthedAppOrgOrgSettingsBillingRoute
  '/app/org/$org/settings/brands': typeof AuthedAppOrgOrgSettingsBrandsRoute
  '/app/org/$org/settings/mcp': typeof AuthedAppOrgOrgSettingsMcpRoute
  '/app/org/$org/settings/members': typeof AuthedAppOrgOrgSettingsMembersRoute
  '/api/v1/brands/$brandId/citations/domains': typeof ApiV1BrandsBrandIdCitationsDomainsRoute
  '/api/v1/brands/$brandId/citations/urls': typeof ApiV1BrandsBrandIdCitationsUrlsRoute
  '/api/v1/prompts/$promptId/runs/$runId': typeof ApiV1PromptsPromptIdRunsRunIdRoute
  '/app/org/$org/settings/': typeof AuthedAppOrgOrgSettingsIndexRoute
  '/api/v1/brands/$brandId/tags/': typeof ApiV1BrandsBrandIdTagsIndexRoute
  '/api/v1/prompts/$promptId/runs/': typeof ApiV1PromptsPromptIdRunsIndexRoute
  '/app/org/$org/brand/$brand/$': typeof AuthedAppOrgOrgBrandBrandSplatRoute
  '/app/org/$org/brand/$brand/citations': typeof AuthedAppOrgOrgBrandBrandCitationsRoute
  '/app/org/$org/brand/$brand/opportunities': typeof AuthedAppOrgOrgBrandBrandOpportunitiesRoute
  '/app/org/$org/brand/$brand/query-fan-out': typeof AuthedAppOrgOrgBrandBrandQueryFanOutRoute
  '/app/org/$org/brand/$brand/share-of-voice': typeof AuthedAppOrgOrgBrandBrandShareOfVoiceRoute
  '/app/org/$org/brand/$brand/visibility': typeof AuthedAppOrgOrgBrandBrandVisibilityRoute
  '/app/org/$org/brand/$brand/': typeof AuthedAppOrgOrgBrandBrandIndexRoute
  '/app/org/$org/brand/$brand/prompts/$promptId': typeof AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute
  '/app/org/$org/brand/$brand/prompts/edit': typeof AuthedAppOrgOrgBrandBrandPromptsEditRoute
  '/app/org/$org/brand/$brand/settings/brand': typeof AuthedAppOrgOrgBrandBrandSettingsBrandRoute
  '/app/org/$org/brand/$brand/settings/competitors': typeof AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute
  '/app/org/$org/brand/$brand/settings/llms': typeof AuthedAppOrgOrgBrandBrandSettingsLlmsRoute
  '/app/org/$org/brand/$brand/settings/prompts': typeof AuthedAppOrgOrgBrandBrandSettingsPromptsRoute
  '/app/org/$org/brand/$brand/prompts/': typeof AuthedAppOrgOrgBrandBrandPromptsIndexRoute
  '/app/org/$org/brand/$brand/settings/': typeof AuthedAppOrgOrgBrandBrandSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-plan': typeof AuthedChoosePlanRoute
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/accept-invitation/$invitationId': typeof AuthedAcceptInvitationInvitationIdRoute
  '/admin/tools': typeof AuthedAdminToolsRoute
  '/admin/workflows': typeof AuthedAdminWorkflowsRoute
  '/app/new': typeof AuthedAppNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerIndexRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceIndexRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/app': typeof AuthedAppIndexRoute
  '/reports': typeof AuthedReportsIndexRoute
  '/api/manifest': typeof ApiManifestIndexRoute
  '/api/og': typeof ApiOgIndexRoute
  '/api/setup-status': typeof ApiSetupStatusIndexRoute
  '/reports/render/$reportId': typeof AuthedReportsRenderReportIdRoute
  '/api/v1/brands/$brandId': typeof ApiV1BrandsBrandIdRouteWithChildren
  '/api/v1/competitors/$competitorId': typeof ApiV1CompetitorsCompetitorIdRoute
  '/api/v1/organizations/$organizationId': typeof ApiV1OrganizationsOrganizationIdRouteWithChildren
  '/api/v1/prompts/$promptId': typeof ApiV1PromptsPromptIdRouteWithChildren
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
  '/api/v1/tools/analyze': typeof ApiV1ToolsAnalyzeRoute
  '/api/plausible/event': typeof ApiPlausibleEventIndexRoute
  '/api/v1/brands': typeof ApiV1BrandsIndexRoute
  '/api/v1/competitors': typeof ApiV1CompetitorsIndexRoute
  '/api/v1/docs': typeof ApiV1DocsIndexRoute
  '/api/v1/organizations': typeof ApiV1OrganizationsIndexRoute
  '/api/v1/prompts': typeof ApiV1PromptsIndexRoute
  '/api/v1/reports': typeof ApiV1ReportsIndexRoute
  '/app/org/$org/new': typeof AuthedAppOrgOrgNewRoute
  '/api/v1/brands/$brandId/analytics': typeof ApiV1BrandsBrandIdAnalyticsRoute
  '/api/v1/brands/$brandId/opportunities': typeof ApiV1BrandsBrandIdOpportunitiesRoute
  '/api/v1/brands/$brandId/prompt-performance': typeof ApiV1BrandsBrandIdPromptPerformanceRoute
  '/api/v1/brands/$brandId/query-fanout': typeof ApiV1BrandsBrandIdQueryFanoutRoute
  '/api/v1/organizations/$organizationId/billing': typeof ApiV1OrganizationsOrganizationIdBillingRoute
  '/api/v1/prompts/$promptId/snapshot': typeof ApiV1PromptsPromptIdSnapshotRoute
  '/app/org/$org': typeof AuthedAppOrgOrgIndexRoute
  '/api/plausible/js/script': typeof ApiPlausibleJsScriptIndexRoute
  '/app/org/$org/settings/api': typeof AuthedAppOrgOrgSettingsApiRoute
  '/app/org/$org/settings/api-keys': typeof AuthedAppOrgOrgSettingsApiKeysRoute
  '/app/org/$org/settings/billing': typeof AuthedAppOrgOrgSettingsBillingRoute
  '/app/org/$org/settings/brands': typeof AuthedAppOrgOrgSettingsBrandsRoute
  '/app/org/$org/settings/mcp': typeof AuthedAppOrgOrgSettingsMcpRoute
  '/app/org/$org/settings/members': typeof AuthedAppOrgOrgSettingsMembersRoute
  '/api/v1/brands/$brandId/citations/domains': typeof ApiV1BrandsBrandIdCitationsDomainsRoute
  '/api/v1/brands/$brandId/citations/urls': typeof ApiV1BrandsBrandIdCitationsUrlsRoute
  '/api/v1/prompts/$promptId/runs/$runId': typeof ApiV1PromptsPromptIdRunsRunIdRoute
  '/app/org/$org/settings': typeof AuthedAppOrgOrgSettingsIndexRoute
  '/api/v1/brands/$brandId/tags': typeof ApiV1BrandsBrandIdTagsIndexRoute
  '/api/v1/prompts/$promptId/runs': typeof ApiV1PromptsPromptIdRunsIndexRoute
  '/app/org/$org/brand/$brand/$': typeof AuthedAppOrgOrgBrandBrandSplatRoute
  '/app/org/$org/brand/$brand/citations': typeof AuthedAppOrgOrgBrandBrandCitationsRoute
  '/app/org/$org/brand/$brand/opportunities': typeof AuthedAppOrgOrgBrandBrandOpportunitiesRoute
  '/app/org/$org/brand/$brand/query-fan-out': typeof AuthedAppOrgOrgBrandBrandQueryFanOutRoute
  '/app/org/$org/brand/$brand/share-of-voice': typeof AuthedAppOrgOrgBrandBrandShareOfVoiceRoute
  '/app/org/$org/brand/$brand/visibility': typeof AuthedAppOrgOrgBrandBrandVisibilityRoute
  '/app/org/$org/brand/$brand': typeof AuthedAppOrgOrgBrandBrandIndexRoute
  '/app/org/$org/brand/$brand/prompts/$promptId': typeof AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute
  '/app/org/$org/brand/$brand/prompts/edit': typeof AuthedAppOrgOrgBrandBrandPromptsEditRoute
  '/app/org/$org/brand/$brand/settings/brand': typeof AuthedAppOrgOrgBrandBrandSettingsBrandRoute
  '/app/org/$org/brand/$brand/settings/competitors': typeof AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute
  '/app/org/$org/brand/$brand/settings/llms': typeof AuthedAppOrgOrgBrandBrandSettingsLlmsRoute
  '/app/org/$org/brand/$brand/settings/prompts': typeof AuthedAppOrgOrgBrandBrandSettingsPromptsRoute
  '/app/org/$org/brand/$brand/prompts': typeof AuthedAppOrgOrgBrandBrandPromptsIndexRoute
  '/app/org/$org/brand/$brand/settings': typeof AuthedAppOrgOrgBrandBrandSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/app': typeof AuthedAppRouteWithChildren
  '/_authed/choose-plan': typeof AuthedChoosePlanRoute
  '/_authed/reports': typeof AuthedReportsRouteWithChildren
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/_authed/accept-invitation/$invitationId': typeof AuthedAcceptInvitationInvitationIdRoute
  '/_authed/admin/tools': typeof AuthedAdminToolsRoute
  '/_authed/admin/workflows': typeof AuthedAdminWorkflowsRoute
  '/_authed/app/new': typeof AuthedAppNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/.well-known/oauth-authorization-server/': typeof DotwellKnownOauthAuthorizationServerIndexRoute
  '/.well-known/oauth-protected-resource/': typeof DotwellKnownOauthProtectedResourceIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
  '/_authed/reports/': typeof AuthedReportsIndexRoute
  '/api/manifest/': typeof ApiManifestIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/api/setup-status/': typeof ApiSetupStatusIndexRoute
  '/_authed/app/org/$org': typeof AuthedAppOrgOrgRouteWithChildren
  '/_authed/reports/render/$reportId': typeof AuthedReportsRenderReportIdRoute
  '/api/v1/brands/$brandId': typeof ApiV1BrandsBrandIdRouteWithChildren
  '/api/v1/competitors/$competitorId': typeof ApiV1CompetitorsCompetitorIdRoute
  '/api/v1/organizations/$organizationId': typeof ApiV1OrganizationsOrganizationIdRouteWithChildren
  '/api/v1/prompts/$promptId': typeof ApiV1PromptsPromptIdRouteWithChildren
  '/api/v1/reports/$reportId': typeof ApiV1ReportsReportIdRoute
  '/api/v1/tools/analyze': typeof ApiV1ToolsAnalyzeRoute
  '/api/plausible/event/': typeof ApiPlausibleEventIndexRoute
  '/api/v1/brands/': typeof ApiV1BrandsIndexRoute
  '/api/v1/competitors/': typeof ApiV1CompetitorsIndexRoute
  '/api/v1/docs/': typeof ApiV1DocsIndexRoute
  '/api/v1/organizations/': typeof ApiV1OrganizationsIndexRoute
  '/api/v1/prompts/': typeof ApiV1PromptsIndexRoute
  '/api/v1/reports/': typeof ApiV1ReportsIndexRoute
  '/_authed/app/org/$org/new': typeof AuthedAppOrgOrgNewRoute
  '/_authed/app/org/$org/settings': typeof AuthedAppOrgOrgSettingsRouteWithChildren
  '/api/v1/brands/$brandId/analytics': typeof ApiV1BrandsBrandIdAnalyticsRoute
  '/api/v1/brands/$brandId/opportunities': typeof ApiV1BrandsBrandIdOpportunitiesRoute
  '/api/v1/brands/$brandId/prompt-performance': typeof ApiV1BrandsBrandIdPromptPerformanceRoute
  '/api/v1/brands/$brandId/query-fanout': typeof ApiV1BrandsBrandIdQueryFanoutRoute
  '/api/v1/organizations/$organizationId/billing': typeof ApiV1OrganizationsOrganizationIdBillingRoute
  '/api/v1/prompts/$promptId/snapshot': typeof ApiV1PromptsPromptIdSnapshotRoute
  '/_authed/app/org/$org/': typeof AuthedAppOrgOrgIndexRoute
  '/api/plausible/js/script/': typeof ApiPlausibleJsScriptIndexRoute
  '/_authed/app/org/$org/brand/$brand': typeof AuthedAppOrgOrgBrandBrandRouteWithChildren
  '/_authed/app/org/$org/settings/api': typeof AuthedAppOrgOrgSettingsApiRoute
  '/_authed/app/org/$org/settings/api-keys': typeof AuthedAppOrgOrgSettingsApiKeysRoute
  '/_authed/app/org/$org/settings/billing': typeof AuthedAppOrgOrgSettingsBillingRoute
  '/_authed/app/org/$org/settings/brands': typeof AuthedAppOrgOrgSettingsBrandsRoute
  '/_authed/app/org/$org/settings/mcp': typeof AuthedAppOrgOrgSettingsMcpRoute
  '/_authed/app/org/$org/settings/members': typeof AuthedAppOrgOrgSettingsMembersRoute
  '/api/v1/brands/$brandId/citations/domains': typeof ApiV1BrandsBrandIdCitationsDomainsRoute
  '/api/v1/brands/$brandId/citations/urls': typeof ApiV1BrandsBrandIdCitationsUrlsRoute
  '/api/v1/prompts/$promptId/runs/$runId': typeof ApiV1PromptsPromptIdRunsRunIdRoute
  '/_authed/app/org/$org/settings/': typeof AuthedAppOrgOrgSettingsIndexRoute
  '/api/v1/brands/$brandId/tags/': typeof ApiV1BrandsBrandIdTagsIndexRoute
  '/api/v1/prompts/$promptId/runs/': typeof ApiV1PromptsPromptIdRunsIndexRoute
  '/_authed/app/org/$org/brand/$brand/$': typeof AuthedAppOrgOrgBrandBrandSplatRoute
  '/_authed/app/org/$org/brand/$brand/citations': typeof AuthedAppOrgOrgBrandBrandCitationsRoute
  '/_authed/app/org/$org/brand/$brand/opportunities': typeof AuthedAppOrgOrgBrandBrandOpportunitiesRoute
  '/_authed/app/org/$org/brand/$brand/query-fan-out': typeof AuthedAppOrgOrgBrandBrandQueryFanOutRoute
  '/_authed/app/org/$org/brand/$brand/share-of-voice': typeof AuthedAppOrgOrgBrandBrandShareOfVoiceRoute
  '/_authed/app/org/$org/brand/$brand/visibility': typeof AuthedAppOrgOrgBrandBrandVisibilityRoute
  '/_authed/app/org/$org/brand/$brand/': typeof AuthedAppOrgOrgBrandBrandIndexRoute
  '/_authed/app/org/$org/brand/$brand/prompts/$promptId': typeof AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute
  '/_authed/app/org/$org/brand/$brand/prompts/edit': typeof AuthedAppOrgOrgBrandBrandPromptsEditRoute
  '/_authed/app/org/$org/brand/$brand/settings/brand': typeof AuthedAppOrgOrgBrandBrandSettingsBrandRoute
  '/_authed/app/org/$org/brand/$brand/settings/competitors': typeof AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute
  '/_authed/app/org/$org/brand/$brand/settings/llms': typeof AuthedAppOrgOrgBrandBrandSettingsLlmsRoute
  '/_authed/app/org/$org/brand/$brand/settings/prompts': typeof AuthedAppOrgOrgBrandBrandSettingsPromptsRoute
  '/_authed/app/org/$org/brand/$brand/prompts/': typeof AuthedAppOrgOrgBrandBrandPromptsIndexRoute
  '/_authed/app/org/$org/brand/$brand/settings/': typeof AuthedAppOrgOrgBrandBrandSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/choose-plan'
    | '/reports'
    | '/auth/authorize'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/accept-invitation/$invitationId'
    | '/admin/tools'
    | '/admin/workflows'
    | '/app/new'
    | '/api/auth/$'
    | '/api/mcp/$'
    | '/api/v1/$'
    | '/api/v1/me'
    | '/api/v1/models'
    | '/.well-known/oauth-authorization-server/'
    | '/.well-known/oauth-protected-resource/'
    | '/admin/'
    | '/app/'
    | '/reports/'
    | '/api/manifest/'
    | '/api/og/'
    | '/api/setup-status/'
    | '/app/org/$org'
    | '/reports/render/$reportId'
    | '/api/v1/brands/$brandId'
    | '/api/v1/competitors/$competitorId'
    | '/api/v1/organizations/$organizationId'
    | '/api/v1/prompts/$promptId'
    | '/api/v1/reports/$reportId'
    | '/api/v1/tools/analyze'
    | '/api/plausible/event/'
    | '/api/v1/brands/'
    | '/api/v1/competitors/'
    | '/api/v1/docs/'
    | '/api/v1/organizations/'
    | '/api/v1/prompts/'
    | '/api/v1/reports/'
    | '/app/org/$org/new'
    | '/app/org/$org/settings'
    | '/api/v1/brands/$brandId/analytics'
    | '/api/v1/brands/$brandId/opportunities'
    | '/api/v1/brands/$brandId/prompt-performance'
    | '/api/v1/brands/$brandId/query-fanout'
    | '/api/v1/organizations/$organizationId/billing'
    | '/api/v1/prompts/$promptId/snapshot'
    | '/app/org/$org/'
    | '/api/plausible/js/script/'
    | '/app/org/$org/brand/$brand'
    | '/app/org/$org/settings/api'
    | '/app/org/$org/settings/api-keys'
    | '/app/org/$org/settings/billing'
    | '/app/org/$org/settings/brands'
    | '/app/org/$org/settings/mcp'
    | '/app/org/$org/settings/members'
    | '/api/v1/brands/$brandId/citations/domains'
    | '/api/v1/brands/$brandId/citations/urls'
    | '/api/v1/prompts/$promptId/runs/$runId'
    | '/app/org/$org/settings/'
    | '/api/v1/brands/$brandId/tags/'
    | '/api/v1/prompts/$promptId/runs/'
    | '/app/org/$org/brand/$brand/$'
    | '/app/org/$org/brand/$brand/citations'
    | '/app/org/$org/brand/$brand/opportunities'
    | '/app/org/$org/brand/$brand/query-fan-out'
    | '/app/org/$org/brand/$brand/share-of-voice'
    | '/app/org/$org/brand/$brand/visibility'
    | '/app/org/$org/brand/$brand/'
    | '/app/org/$org/brand/$brand/prompts/$promptId'
    | '/app/org/$org/brand/$brand/prompts/edit'
    | '/app/org/$org/brand/$brand/settings/brand'
    | '/app/org/$org/brand/$brand/settings/competitors'
    | '/app/org/$org/brand/$brand/settings/llms'
    | '/app/org/$org/brand/$brand/settings/prompts'
    | '/app/org/$org/brand/$brand/prompts/'
    | '/app/org/$org/brand/$brand/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-plan'
    | '/auth/authorize'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/accept-invitation/$invitationId'
    | '/admin/tools'
    | '/admin/workflows'
    | '/app/new'
    | '/api/auth/$'
    | '/api/mcp/$'
    | '/api/v1/$'
    | '/api/v1/me'
    | '/api/v1/models'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/app'
    | '/reports'
    | '/api/manifest'
    | '/api/og'
    | '/api/setup-status'
    | '/reports/render/$reportId'
    | '/api/v1/brands/$brandId'
    | '/api/v1/competitors/$competitorId'
    | '/api/v1/organizations/$organizationId'
    | '/api/v1/prompts/$promptId'
    | '/api/v1/reports/$reportId'
    | '/api/v1/tools/analyze'
    | '/api/plausible/event'
    | '/api/v1/brands'
    | '/api/v1/competitors'
    | '/api/v1/docs'
    | '/api/v1/organizations'
    | '/api/v1/prompts'
    | '/api/v1/reports'
    | '/app/org/$org/new'
    | '/api/v1/brands/$brandId/analytics'
    | '/api/v1/brands/$brandId/opportunities'
    | '/api/v1/brands/$brandId/prompt-performance'
    | '/api/v1/brands/$brandId/query-fanout'
    | '/api/v1/organizations/$organizationId/billing'
    | '/api/v1/prompts/$promptId/snapshot'
    | '/app/org/$org'
    | '/api/plausible/js/script'
    | '/app/org/$org/settings/api'
    | '/app/org/$org/settings/api-keys'
    | '/app/org/$org/settings/billing'
    | '/app/org/$org/settings/brands'
    | '/app/org/$org/settings/mcp'
    | '/app/org/$org/settings/members'
    | '/api/v1/brands/$brandId/citations/domains'
    | '/api/v1/brands/$brandId/citations/urls'
    | '/api/v1/prompts/$promptId/runs/$runId'
    | '/app/org/$org/settings'
    | '/api/v1/brands/$brandId/tags'
    | '/api/v1/prompts/$promptId/runs'
    | '/app/org/$org/brand/$brand/$'
    | '/app/org/$org/brand/$brand/citations'
    | '/app/org/$org/brand/$brand/opportunities'
    | '/app/org/$org/brand/$brand/query-fan-out'
    | '/app/org/$org/brand/$brand/share-of-voice'
    | '/app/org/$org/brand/$brand/visibility'
    | '/app/org/$org/brand/$brand'
    | '/app/org/$org/brand/$brand/prompts/$promptId'
    | '/app/org/$org/brand/$brand/prompts/edit'
    | '/app/org/$org/brand/$brand/settings/brand'
    | '/app/org/$org/brand/$brand/settings/competitors'
    | '/app/org/$org/brand/$brand/settings/llms'
    | '/app/org/$org/brand/$brand/settings/prompts'
    | '/app/org/$org/brand/$brand/prompts'
    | '/app/org/$org/brand/$brand/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/admin'
    | '/_authed/app'
    | '/_authed/choose-plan'
    | '/_authed/reports'
    | '/auth/authorize'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/_authed/accept-invitation/$invitationId'
    | '/_authed/admin/tools'
    | '/_authed/admin/workflows'
    | '/_authed/app/new'
    | '/api/auth/$'
    | '/api/mcp/$'
    | '/api/v1/$'
    | '/api/v1/me'
    | '/api/v1/models'
    | '/.well-known/oauth-authorization-server/'
    | '/.well-known/oauth-protected-resource/'
    | '/_authed/admin/'
    | '/_authed/app/'
    | '/_authed/reports/'
    | '/api/manifest/'
    | '/api/og/'
    | '/api/setup-status/'
    | '/_authed/app/org/$org'
    | '/_authed/reports/render/$reportId'
    | '/api/v1/brands/$brandId'
    | '/api/v1/competitors/$competitorId'
    | '/api/v1/organizations/$organizationId'
    | '/api/v1/prompts/$promptId'
    | '/api/v1/reports/$reportId'
    | '/api/v1/tools/analyze'
    | '/api/plausible/event/'
    | '/api/v1/brands/'
    | '/api/v1/competitors/'
    | '/api/v1/docs/'
    | '/api/v1/organizations/'
    | '/api/v1/prompts/'
    | '/api/v1/reports/'
    | '/_authed/app/org/$org/new'
    | '/_authed/app/org/$org/settings'
    | '/api/v1/brands/$brandId/analytics'
    | '/api/v1/brands/$brandId/opportunities'
    | '/api/v1/brands/$brandId/prompt-performance'
    | '/api/v1/brands/$brandId/query-fanout'
    | '/api/v1/organizations/$organizationId/billing'
    | '/api/v1/prompts/$promptId/snapshot'
    | '/_authed/app/org/$org/'
    | '/api/plausible/js/script/'
    | '/_authed/app/org/$org/brand/$brand'
    | '/_authed/app/org/$org/settings/api'
    | '/_authed/app/org/$org/settings/api-keys'
    | '/_authed/app/org/$org/settings/billing'
    | '/_authed/app/org/$org/settings/brands'
    | '/_authed/app/org/$org/settings/mcp'
    | '/_authed/app/org/$org/settings/members'
    | '/api/v1/brands/$brandId/citations/domains'
    | '/api/v1/brands/$brandId/citations/urls'
    | '/api/v1/prompts/$promptId/runs/$runId'
    | '/_authed/app/org/$org/settings/'
    | '/api/v1/brands/$brandId/tags/'
    | '/api/v1/prompts/$promptId/runs/'
    | '/_authed/app/org/$org/brand/$brand/$'
    | '/_authed/app/org/$org/brand/$brand/citations'
    | '/_authed/app/org/$org/brand/$brand/opportunities'
    | '/_authed/app/org/$org/brand/$brand/query-fan-out'
    | '/_authed/app/org/$org/brand/$brand/share-of-voice'
    | '/_authed/app/org/$org/brand/$brand/visibility'
    | '/_authed/app/org/$org/brand/$brand/'
    | '/_authed/app/org/$org/brand/$brand/prompts/$promptId'
    | '/_authed/app/org/$org/brand/$brand/prompts/edit'
    | '/_authed/app/org/$org/brand/$brand/settings/brand'
    | '/_authed/app/org/$org/brand/$brand/settings/competitors'
    | '/_authed/app/org/$org/brand/$brand/settings/llms'
    | '/_authed/app/org/$org/brand/$brand/settings/prompts'
    | '/_authed/app/org/$org/brand/$brand/prompts/'
    | '/_authed/app/org/$org/brand/$brand/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthAuthorizeRoute: typeof AuthAuthorizeRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute
  DotwellKnownOauthProtectedResourceSplatRoute: typeof DotwellKnownOauthProtectedResourceSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMcpSplatRoute: typeof ApiMcpSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1ModelsRoute: typeof ApiV1ModelsRoute
  DotwellKnownOauthAuthorizationServerIndexRoute: typeof DotwellKnownOauthAuthorizationServerIndexRoute
  DotwellKnownOauthProtectedResourceIndexRoute: typeof DotwellKnownOauthProtectedResourceIndexRoute
  ApiManifestIndexRoute: typeof ApiManifestIndexRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
  ApiSetupStatusIndexRoute: typeof ApiSetupStatusIndexRoute
  ApiV1BrandsBrandIdRoute: typeof ApiV1BrandsBrandIdRouteWithChildren
  ApiV1CompetitorsCompetitorIdRoute: typeof ApiV1CompetitorsCompetitorIdRoute
  ApiV1OrganizationsOrganizationIdRoute: typeof ApiV1OrganizationsOrganizationIdRouteWithChildren
  ApiV1PromptsPromptIdRoute: typeof ApiV1PromptsPromptIdRouteWithChildren
  ApiV1ReportsReportIdRoute: typeof ApiV1ReportsReportIdRoute
  ApiV1ToolsAnalyzeRoute: typeof ApiV1ToolsAnalyzeRoute
  ApiPlausibleEventIndexRoute: typeof ApiPlausibleEventIndexRoute
  ApiV1BrandsIndexRoute: typeof ApiV1BrandsIndexRoute
  ApiV1CompetitorsIndexRoute: typeof ApiV1CompetitorsIndexRoute
  ApiV1DocsIndexRoute: typeof ApiV1DocsIndexRoute
  ApiV1OrganizationsIndexRoute: typeof ApiV1OrganizationsIndexRoute
  ApiV1PromptsIndexRoute: typeof ApiV1PromptsIndexRoute
  ApiV1ReportsIndexRoute: typeof ApiV1ReportsIndexRoute
  ApiPlausibleJsScriptIndexRoute: typeof ApiPlausibleJsScriptIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/choose-plan': {
      id: '/_authed/choose-plan'
      path: '/choose-plan'
      fullPath: '/choose-plan'
      preLoaderRoute: typeof AuthedChoosePlanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/authorize': {
      id: '/auth/authorize'
      path: '/auth/authorize'
      fullPath: '/auth/authorize'
      preLoaderRoute: typeof AuthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/': {
      id: '/.well-known/oauth-authorization-server/'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server/'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/.well-known/oauth-authorization-server/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/': {
      id: '/.well-known/oauth-protected-resource/'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource/'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/$': {
      id: '/.well-known/oauth-protected-resource/$'
      path: '/.well-known/oauth-protected-resource/$'
      fullPath: '/.well-known/oauth-protected-resource/$'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/accept-invitation/$invitationId': {
      id: '/_authed/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthedAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/tools': {
      id: '/_authed/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthedAdminToolsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/workflows': {
      id: '/_authed/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthedAdminWorkflowsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/new': {
      id: '/_authed/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthedAppNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/reports/': {
      id: '/_authed/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthedReportsIndexRouteImport
      parentRoute: typeof AuthedReportsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest/': {
      id: '/api/manifest/'
      path: '/api/manifest'
      fullPath: '/api/manifest/'
      preLoaderRoute: typeof ApiManifestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$': {
      id: '/api/mcp/$'
      path: '/api/mcp/$'
      fullPath: '/api/mcp/$'
      preLoaderRoute: typeof ApiMcpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-status/': {
      id: '/api/setup-status/'
      path: '/api/setup-status'
      fullPath: '/api/setup-status/'
      preLoaderRoute: typeof ApiSetupStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models': {
      id: '/api/v1/models'
      path: '/api/v1/models'
      fullPath: '/api/v1/models'
      preLoaderRoute: typeof ApiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/org/$org': {
      id: '/_authed/app/org/$org'
      path: '/org/$org'
      fullPath: '/app/org/$org'
      preLoaderRoute: typeof AuthedAppOrgOrgRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/reports/render/$reportId': {
      id: '/_authed/reports/render/$reportId'
      path: '/render/$reportId'
      fullPath: '/reports/render/$reportId'
      preLoaderRoute: typeof AuthedReportsRenderReportIdRouteImport
      parentRoute: typeof AuthedReportsRoute
    }
    '/api/plausible/event/': {
      id: '/api/plausible/event/'
      path: '/api/plausible/event'
      fullPath: '/api/plausible/event/'
      preLoaderRoute: typeof ApiPlausibleEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brands/': {
      id: '/api/v1/brands/'
      path: '/api/v1/brands'
      fullPath: '/api/v1/brands/'
      preLoaderRoute: typeof ApiV1BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brands/$brandId': {
      id: '/api/v1/brands/$brandId'
      path: '/api/v1/brands/$brandId'
      fullPath: '/api/v1/brands/$brandId'
      preLoaderRoute: typeof ApiV1BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/competitors/': {
      id: '/api/v1/competitors/'
      path: '/api/v1/competitors'
      fullPath: '/api/v1/competitors/'
      preLoaderRoute: typeof ApiV1CompetitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/competitors/$competitorId': {
      id: '/api/v1/competitors/$competitorId'
      path: '/api/v1/competitors/$competitorId'
      fullPath: '/api/v1/competitors/$competitorId'
      preLoaderRoute: typeof ApiV1CompetitorsCompetitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/docs/': {
      id: '/api/v1/docs/'
      path: '/api/v1/docs'
      fullPath: '/api/v1/docs/'
      preLoaderRoute: typeof ApiV1DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/': {
      id: '/api/v1/organizations/'
      path: '/api/v1/organizations'
      fullPath: '/api/v1/organizations/'
      preLoaderRoute: typeof ApiV1OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/$organizationId': {
      id: '/api/v1/organizations/$organizationId'
      path: '/api/v1/organizations/$organizationId'
      fullPath: '/api/v1/organizations/$organizationId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/prompts/': {
      id: '/api/v1/prompts/'
      path: '/api/v1/prompts'
      fullPath: '/api/v1/prompts/'
      preLoaderRoute: typeof ApiV1PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/prompts/$promptId': {
      id: '/api/v1/prompts/$promptId'
      path: '/api/v1/prompts/$promptId'
      fullPath: '/api/v1/prompts/$promptId'
      preLoaderRoute: typeof ApiV1PromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/': {
      id: '/api/v1/reports/'
      path: '/api/v1/reports'
      fullPath: '/api/v1/reports/'
      preLoaderRoute: typeof ApiV1ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/$reportId': {
      id: '/api/v1/reports/$reportId'
      path: '/api/v1/reports/$reportId'
      fullPath: '/api/v1/reports/$reportId'
      preLoaderRoute: typeof ApiV1ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tools/analyze': {
      id: '/api/v1/tools/analyze'
      path: '/api/v1/tools/analyze'
      fullPath: '/api/v1/tools/analyze'
      preLoaderRoute: typeof ApiV1ToolsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/org/$org/': {
      id: '/_authed/app/org/$org/'
      path: '/'
      fullPath: '/app/org/$org/'
      preLoaderRoute: typeof AuthedAppOrgOrgIndexRouteImport
      parentRoute: typeof AuthedAppOrgOrgRoute
    }
    '/_authed/app/org/$org/new': {
      id: '/_authed/app/org/$org/new'
      path: '/new'
      fullPath: '/app/org/$org/new'
      preLoaderRoute: typeof AuthedAppOrgOrgNewRouteImport
      parentRoute: typeof AuthedAppOrgOrgRoute
    }
    '/_authed/app/org/$org/settings': {
      id: '/_authed/app/org/$org/settings'
      path: '/settings'
      fullPath: '/app/org/$org/settings'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsRouteImport
      parentRoute: typeof AuthedAppOrgOrgRoute
    }
    '/api/plausible/js/script/': {
      id: '/api/plausible/js/script/'
      path: '/api/plausible/js/script'
      fullPath: '/api/plausible/js/script/'
      preLoaderRoute: typeof ApiPlausibleJsScriptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brands/$brandId/analytics': {
      id: '/api/v1/brands/$brandId/analytics'
      path: '/analytics'
      fullPath: '/api/v1/brands/$brandId/analytics'
      preLoaderRoute: typeof ApiV1BrandsBrandIdAnalyticsRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/brands/$brandId/opportunities': {
      id: '/api/v1/brands/$brandId/opportunities'
      path: '/opportunities'
      fullPath: '/api/v1/brands/$brandId/opportunities'
      preLoaderRoute: typeof ApiV1BrandsBrandIdOpportunitiesRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/brands/$brandId/prompt-performance': {
      id: '/api/v1/brands/$brandId/prompt-performance'
      path: '/prompt-performance'
      fullPath: '/api/v1/brands/$brandId/prompt-performance'
      preLoaderRoute: typeof ApiV1BrandsBrandIdPromptPerformanceRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/brands/$brandId/query-fanout': {
      id: '/api/v1/brands/$brandId/query-fanout'
      path: '/query-fanout'
      fullPath: '/api/v1/brands/$brandId/query-fanout'
      preLoaderRoute: typeof ApiV1BrandsBrandIdQueryFanoutRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/organizations/$organizationId/billing': {
      id: '/api/v1/organizations/$organizationId/billing'
      path: '/billing'
      fullPath: '/api/v1/organizations/$organizationId/billing'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdBillingRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdRoute
    }
    '/api/v1/prompts/$promptId/snapshot': {
      id: '/api/v1/prompts/$promptId/snapshot'
      path: '/snapshot'
      fullPath: '/api/v1/prompts/$promptId/snapshot'
      preLoaderRoute: typeof ApiV1PromptsPromptIdSnapshotRouteImport
      parentRoute: typeof ApiV1PromptsPromptIdRoute
    }
    '/_authed/app/org/$org/brand/$brand': {
      id: '/_authed/app/org/$org/brand/$brand'
      path: '/brand/$brand'
      fullPath: '/app/org/$org/brand/$brand'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandRouteImport
      parentRoute: typeof AuthedAppOrgOrgRoute
    }
    '/_authed/app/org/$org/settings/': {
      id: '/_authed/app/org/$org/settings/'
      path: '/'
      fullPath: '/app/org/$org/settings/'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsIndexRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/_authed/app/org/$org/settings/api': {
      id: '/_authed/app/org/$org/settings/api'
      path: '/api'
      fullPath: '/app/org/$org/settings/api'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsApiRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/_authed/app/org/$org/settings/api-keys': {
      id: '/_authed/app/org/$org/settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/org/$org/settings/api-keys'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsApiKeysRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/_authed/app/org/$org/settings/billing': {
      id: '/_authed/app/org/$org/settings/billing'
      path: '/billing'
      fullPath: '/app/org/$org/settings/billing'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsBillingRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/_authed/app/org/$org/settings/brands': {
      id: '/_authed/app/org/$org/settings/brands'
      path: '/brands'
      fullPath: '/app/org/$org/settings/brands'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsBrandsRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/_authed/app/org/$org/settings/mcp': {
      id: '/_authed/app/org/$org/settings/mcp'
      path: '/mcp'
      fullPath: '/app/org/$org/settings/mcp'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsMcpRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/_authed/app/org/$org/settings/members': {
      id: '/_authed/app/org/$org/settings/members'
      path: '/members'
      fullPath: '/app/org/$org/settings/members'
      preLoaderRoute: typeof AuthedAppOrgOrgSettingsMembersRouteImport
      parentRoute: typeof AuthedAppOrgOrgSettingsRoute
    }
    '/api/v1/brands/$brandId/citations/domains': {
      id: '/api/v1/brands/$brandId/citations/domains'
      path: '/citations/domains'
      fullPath: '/api/v1/brands/$brandId/citations/domains'
      preLoaderRoute: typeof ApiV1BrandsBrandIdCitationsDomainsRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/brands/$brandId/citations/urls': {
      id: '/api/v1/brands/$brandId/citations/urls'
      path: '/citations/urls'
      fullPath: '/api/v1/brands/$brandId/citations/urls'
      preLoaderRoute: typeof ApiV1BrandsBrandIdCitationsUrlsRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/brands/$brandId/tags/': {
      id: '/api/v1/brands/$brandId/tags/'
      path: '/tags'
      fullPath: '/api/v1/brands/$brandId/tags/'
      preLoaderRoute: typeof ApiV1BrandsBrandIdTagsIndexRouteImport
      parentRoute: typeof ApiV1BrandsBrandIdRoute
    }
    '/api/v1/prompts/$promptId/runs/': {
      id: '/api/v1/prompts/$promptId/runs/'
      path: '/runs'
      fullPath: '/api/v1/prompts/$promptId/runs/'
      preLoaderRoute: typeof ApiV1PromptsPromptIdRunsIndexRouteImport
      parentRoute: typeof ApiV1PromptsPromptIdRoute
    }
    '/api/v1/prompts/$promptId/runs/$runId': {
      id: '/api/v1/prompts/$promptId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/api/v1/prompts/$promptId/runs/$runId'
      preLoaderRoute: typeof ApiV1PromptsPromptIdRunsRunIdRouteImport
      parentRoute: typeof ApiV1PromptsPromptIdRoute
    }
    '/_authed/app/org/$org/brand/$brand/': {
      id: '/_authed/app/org/$org/brand/$brand/'
      path: '/'
      fullPath: '/app/org/$org/brand/$brand/'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandIndexRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/$': {
      id: '/_authed/app/org/$org/brand/$brand/$'
      path: '/$'
      fullPath: '/app/org/$org/brand/$brand/$'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandSplatRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/citations': {
      id: '/_authed/app/org/$org/brand/$brand/citations'
      path: '/citations'
      fullPath: '/app/org/$org/brand/$brand/citations'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandCitationsRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/opportunities': {
      id: '/_authed/app/org/$org/brand/$brand/opportunities'
      path: '/opportunities'
      fullPath: '/app/org/$org/brand/$brand/opportunities'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandOpportunitiesRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/query-fan-out': {
      id: '/_authed/app/org/$org/brand/$brand/query-fan-out'
      path: '/query-fan-out'
      fullPath: '/app/org/$org/brand/$brand/query-fan-out'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandQueryFanOutRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/share-of-voice': {
      id: '/_authed/app/org/$org/brand/$brand/share-of-voice'
      path: '/share-of-voice'
      fullPath: '/app/org/$org/brand/$brand/share-of-voice'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandShareOfVoiceRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/visibility': {
      id: '/_authed/app/org/$org/brand/$brand/visibility'
      path: '/visibility'
      fullPath: '/app/org/$org/brand/$brand/visibility'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandVisibilityRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/prompts/': {
      id: '/_authed/app/org/$org/brand/$brand/prompts/'
      path: '/prompts'
      fullPath: '/app/org/$org/brand/$brand/prompts/'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandPromptsIndexRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/prompts/$promptId': {
      id: '/_authed/app/org/$org/brand/$brand/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/app/org/$org/brand/$brand/prompts/$promptId'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandPromptsPromptIdRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/prompts/edit': {
      id: '/_authed/app/org/$org/brand/$brand/prompts/edit'
      path: '/prompts/edit'
      fullPath: '/app/org/$org/brand/$brand/prompts/edit'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandPromptsEditRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/settings/': {
      id: '/_authed/app/org/$org/brand/$brand/settings/'
      path: '/settings'
      fullPath: '/app/org/$org/brand/$brand/settings/'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandSettingsIndexRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/settings/brand': {
      id: '/_authed/app/org/$org/brand/$brand/settings/brand'
      path: '/settings/brand'
      fullPath: '/app/org/$org/brand/$brand/settings/brand'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandSettingsBrandRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/settings/competitors': {
      id: '/_authed/app/org/$org/brand/$brand/settings/competitors'
      path: '/settings/competitors'
      fullPath: '/app/org/$org/brand/$brand/settings/competitors'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandSettingsCompetitorsRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/settings/llms': {
      id: '/_authed/app/org/$org/brand/$brand/settings/llms'
      path: '/settings/llms'
      fullPath: '/app/org/$org/brand/$brand/settings/llms'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandSettingsLlmsRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
    '/_authed/app/org/$org/brand/$brand/settings/prompts': {
      id: '/_authed/app/org/$org/brand/$brand/settings/prompts'
      path: '/settings/prompts'
      fullPath: '/app/org/$org/brand/$brand/settings/prompts'
      preLoaderRoute: typeof AuthedAppOrgOrgBrandBrandSettingsPromptsRouteImport
      parentRoute: typeof AuthedAppOrgOrgBrandBrandRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminToolsRoute: typeof AuthedAdminToolsRoute
  AuthedAdminWorkflowsRoute: typeof AuthedAdminWorkflowsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminToolsRoute: AuthedAdminToolsRoute,
  AuthedAdminWorkflowsRoute: AuthedAdminWorkflowsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedAppOrgOrgSettingsRouteChildren {
  AuthedAppOrgOrgSettingsApiRoute: typeof AuthedAppOrgOrgSettingsApiRoute
  AuthedAppOrgOrgSettingsApiKeysRoute: typeof AuthedAppOrgOrgSettingsApiKeysRoute
  AuthedAppOrgOrgSettingsBillingRoute: typeof AuthedAppOrgOrgSettingsBillingRoute
  AuthedAppOrgOrgSettingsBrandsRoute: typeof AuthedAppOrgOrgSettingsBrandsRoute
  AuthedAppOrgOrgSettingsMcpRoute: typeof AuthedAppOrgOrgSettingsMcpRoute
  AuthedAppOrgOrgSettingsMembersRoute: typeof AuthedAppOrgOrgSettingsMembersRoute
  AuthedAppOrgOrgSettingsIndexRoute: typeof AuthedAppOrgOrgSettingsIndexRoute
}

const AuthedAppOrgOrgSettingsRouteChildren: AuthedAppOrgOrgSettingsRouteChildren =
  {
    AuthedAppOrgOrgSettingsApiRoute: AuthedAppOrgOrgSettingsApiRoute,
    AuthedAppOrgOrgSettingsApiKeysRoute: AuthedAppOrgOrgSettingsApiKeysRoute,
    AuthedAppOrgOrgSettingsBillingRoute: AuthedAppOrgOrgSettingsBillingRoute,
    AuthedAppOrgOrgSettingsBrandsRoute: AuthedAppOrgOrgSettingsBrandsRoute,
    AuthedAppOrgOrgSettingsMcpRoute: AuthedAppOrgOrgSettingsMcpRoute,
    AuthedAppOrgOrgSettingsMembersRoute: AuthedAppOrgOrgSettingsMembersRoute,
    AuthedAppOrgOrgSettingsIndexRoute: AuthedAppOrgOrgSettingsIndexRoute,
  }

const AuthedAppOrgOrgSettingsRouteWithChildren =
  AuthedAppOrgOrgSettingsRoute._addFileChildren(
    AuthedAppOrgOrgSettingsRouteChildren,
  )

interface AuthedAppOrgOrgBrandBrandRouteChildren {
  AuthedAppOrgOrgBrandBrandSplatRoute: typeof AuthedAppOrgOrgBrandBrandSplatRoute
  AuthedAppOrgOrgBrandBrandCitationsRoute: typeof AuthedAppOrgOrgBrandBrandCitationsRoute
  AuthedAppOrgOrgBrandBrandOpportunitiesRoute: typeof AuthedAppOrgOrgBrandBrandOpportunitiesRoute
  AuthedAppOrgOrgBrandBrandQueryFanOutRoute: typeof AuthedAppOrgOrgBrandBrandQueryFanOutRoute
  AuthedAppOrgOrgBrandBrandShareOfVoiceRoute: typeof AuthedAppOrgOrgBrandBrandShareOfVoiceRoute
  AuthedAppOrgOrgBrandBrandVisibilityRoute: typeof AuthedAppOrgOrgBrandBrandVisibilityRoute
  AuthedAppOrgOrgBrandBrandIndexRoute: typeof AuthedAppOrgOrgBrandBrandIndexRoute
  AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute: typeof AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute
  AuthedAppOrgOrgBrandBrandPromptsEditRoute: typeof AuthedAppOrgOrgBrandBrandPromptsEditRoute
  AuthedAppOrgOrgBrandBrandSettingsBrandRoute: typeof AuthedAppOrgOrgBrandBrandSettingsBrandRoute
  AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute: typeof AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute
  AuthedAppOrgOrgBrandBrandSettingsLlmsRoute: typeof AuthedAppOrgOrgBrandBrandSettingsLlmsRoute
  AuthedAppOrgOrgBrandBrandSettingsPromptsRoute: typeof AuthedAppOrgOrgBrandBrandSettingsPromptsRoute
  AuthedAppOrgOrgBrandBrandPromptsIndexRoute: typeof AuthedAppOrgOrgBrandBrandPromptsIndexRoute
  AuthedAppOrgOrgBrandBrandSettingsIndexRoute: typeof AuthedAppOrgOrgBrandBrandSettingsIndexRoute
}

const AuthedAppOrgOrgBrandBrandRouteChildren: AuthedAppOrgOrgBrandBrandRouteChildren =
  {
    AuthedAppOrgOrgBrandBrandSplatRoute: AuthedAppOrgOrgBrandBrandSplatRoute,
    AuthedAppOrgOrgBrandBrandCitationsRoute:
      AuthedAppOrgOrgBrandBrandCitationsRoute,
    AuthedAppOrgOrgBrandBrandOpportunitiesRoute:
      AuthedAppOrgOrgBrandBrandOpportunitiesRoute,
    AuthedAppOrgOrgBrandBrandQueryFanOutRoute:
      AuthedAppOrgOrgBrandBrandQueryFanOutRoute,
    AuthedAppOrgOrgBrandBrandShareOfVoiceRoute:
      AuthedAppOrgOrgBrandBrandShareOfVoiceRoute,
    AuthedAppOrgOrgBrandBrandVisibilityRoute:
      AuthedAppOrgOrgBrandBrandVisibilityRoute,
    AuthedAppOrgOrgBrandBrandIndexRoute: AuthedAppOrgOrgBrandBrandIndexRoute,
    AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute:
      AuthedAppOrgOrgBrandBrandPromptsPromptIdRoute,
    AuthedAppOrgOrgBrandBrandPromptsEditRoute:
      AuthedAppOrgOrgBrandBrandPromptsEditRoute,
    AuthedAppOrgOrgBrandBrandSettingsBrandRoute:
      AuthedAppOrgOrgBrandBrandSettingsBrandRoute,
    AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute:
      AuthedAppOrgOrgBrandBrandSettingsCompetitorsRoute,
    AuthedAppOrgOrgBrandBrandSettingsLlmsRoute:
      AuthedAppOrgOrgBrandBrandSettingsLlmsRoute,
    AuthedAppOrgOrgBrandBrandSettingsPromptsRoute:
      AuthedAppOrgOrgBrandBrandSettingsPromptsRoute,
    AuthedAppOrgOrgBrandBrandPromptsIndexRoute:
      AuthedAppOrgOrgBrandBrandPromptsIndexRoute,
    AuthedAppOrgOrgBrandBrandSettingsIndexRoute:
      AuthedAppOrgOrgBrandBrandSettingsIndexRoute,
  }

const AuthedAppOrgOrgBrandBrandRouteWithChildren =
  AuthedAppOrgOrgBrandBrandRoute._addFileChildren(
    AuthedAppOrgOrgBrandBrandRouteChildren,
  )

interface AuthedAppOrgOrgRouteChildren {
  AuthedAppOrgOrgNewRoute: typeof AuthedAppOrgOrgNewRoute
  AuthedAppOrgOrgSettingsRoute: typeof AuthedAppOrgOrgSettingsRouteWithChildren
  AuthedAppOrgOrgIndexRoute: typeof AuthedAppOrgOrgIndexRoute
  AuthedAppOrgOrgBrandBrandRoute: typeof AuthedAppOrgOrgBrandBrandRouteWithChildren
}

const AuthedAppOrgOrgRouteChildren: AuthedAppOrgOrgRouteChildren = {
  AuthedAppOrgOrgNewRoute: AuthedAppOrgOrgNewRoute,
  AuthedAppOrgOrgSettingsRoute: AuthedAppOrgOrgSettingsRouteWithChildren,
  AuthedAppOrgOrgIndexRoute: AuthedAppOrgOrgIndexRoute,
  AuthedAppOrgOrgBrandBrandRoute: AuthedAppOrgOrgBrandBrandRouteWithChildren,
}

const AuthedAppOrgOrgRouteWithChildren = AuthedAppOrgOrgRoute._addFileChildren(
  AuthedAppOrgOrgRouteChildren,
)

interface AuthedAppRouteChildren {
  AuthedAppNewRoute: typeof AuthedAppNewRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppOrgOrgRoute: typeof AuthedAppOrgOrgRouteWithChildren
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppNewRoute: AuthedAppNewRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppOrgOrgRoute: AuthedAppOrgOrgRouteWithChildren,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedReportsRouteChildren {
  AuthedReportsIndexRoute: typeof AuthedReportsIndexRoute
  AuthedReportsRenderReportIdRoute: typeof AuthedReportsRenderReportIdRoute
}

const AuthedReportsRouteChildren: AuthedReportsRouteChildren = {
  AuthedReportsIndexRoute: AuthedReportsIndexRoute,
  AuthedReportsRenderReportIdRoute: AuthedReportsRenderReportIdRoute,
}

const AuthedReportsRouteWithChildren = AuthedReportsRoute._addFileChildren(
  AuthedReportsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedChoosePlanRoute: typeof AuthedChoosePlanRoute
  AuthedReportsRoute: typeof AuthedReportsRouteWithChildren
  AuthedAcceptInvitationInvitationIdRoute: typeof AuthedAcceptInvitationInvitationIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedChoosePlanRoute: AuthedChoosePlanRoute,
  AuthedReportsRoute: AuthedReportsRouteWithChildren,
  AuthedAcceptInvitationInvitationIdRoute:
    AuthedAcceptInvitationInvitationIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiV1BrandsBrandIdRouteChildren {
  ApiV1BrandsBrandIdAnalyticsRoute: typeof ApiV1BrandsBrandIdAnalyticsRoute
  ApiV1BrandsBrandIdOpportunitiesRoute: typeof ApiV1BrandsBrandIdOpportunitiesRoute
  ApiV1BrandsBrandIdPromptPerformanceRoute: typeof ApiV1BrandsBrandIdPromptPerformanceRoute
  ApiV1BrandsBrandIdQueryFanoutRoute: typeof ApiV1BrandsBrandIdQueryFanoutRoute
  ApiV1BrandsBrandIdCitationsDomainsRoute: typeof ApiV1BrandsBrandIdCitationsDomainsRoute
  ApiV1BrandsBrandIdCitationsUrlsRoute: typeof ApiV1BrandsBrandIdCitationsUrlsRoute
  ApiV1BrandsBrandIdTagsIndexRoute: typeof ApiV1BrandsBrandIdTagsIndexRoute
}

const ApiV1BrandsBrandIdRouteChildren: ApiV1BrandsBrandIdRouteChildren = {
  ApiV1BrandsBrandIdAnalyticsRoute: ApiV1BrandsBrandIdAnalyticsRoute,
  ApiV1BrandsBrandIdOpportunitiesRoute: ApiV1BrandsBrandIdOpportunitiesRoute,
  ApiV1BrandsBrandIdPromptPerformanceRoute:
    ApiV1BrandsBrandIdPromptPerformanceRoute,
  ApiV1BrandsBrandIdQueryFanoutRoute: ApiV1BrandsBrandIdQueryFanoutRoute,
  ApiV1BrandsBrandIdCitationsDomainsRoute:
    ApiV1BrandsBrandIdCitationsDomainsRoute,
  ApiV1BrandsBrandIdCitationsUrlsRoute: ApiV1BrandsBrandIdCitationsUrlsRoute,
  ApiV1BrandsBrandIdTagsIndexRoute: ApiV1BrandsBrandIdTagsIndexRoute,
}

const ApiV1BrandsBrandIdRouteWithChildren =
  ApiV1BrandsBrandIdRoute._addFileChildren(ApiV1BrandsBrandIdRouteChildren)

interface ApiV1OrganizationsOrganizationIdRouteChildren {
  ApiV1OrganizationsOrganizationIdBillingRoute: typeof ApiV1OrganizationsOrganizationIdBillingRoute
}

const ApiV1OrganizationsOrganizationIdRouteChildren: ApiV1OrganizationsOrganizationIdRouteChildren =
  {
    ApiV1OrganizationsOrganizationIdBillingRoute:
      ApiV1OrganizationsOrganizationIdBillingRoute,
  }

const ApiV1OrganizationsOrganizationIdRouteWithChildren =
  ApiV1OrganizationsOrganizationIdRoute._addFileChildren(
    ApiV1OrganizationsOrganizationIdRouteChildren,
  )

interface ApiV1PromptsPromptIdRouteChildren {
  ApiV1PromptsPromptIdSnapshotRoute: typeof ApiV1PromptsPromptIdSnapshotRoute
  ApiV1PromptsPromptIdRunsRunIdRoute: typeof ApiV1PromptsPromptIdRunsRunIdRoute
  ApiV1PromptsPromptIdRunsIndexRoute: typeof ApiV1PromptsPromptIdRunsIndexRoute
}

const ApiV1PromptsPromptIdRouteChildren: ApiV1PromptsPromptIdRouteChildren = {
  ApiV1PromptsPromptIdSnapshotRoute: ApiV1PromptsPromptIdSnapshotRoute,
  ApiV1PromptsPromptIdRunsRunIdRoute: ApiV1PromptsPromptIdRunsRunIdRoute,
  ApiV1PromptsPromptIdRunsIndexRoute: ApiV1PromptsPromptIdRunsIndexRoute,
}

const ApiV1PromptsPromptIdRouteWithChildren =
  ApiV1PromptsPromptIdRoute._addFileChildren(ApiV1PromptsPromptIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthAuthorizeRoute: AuthAuthorizeRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  DotwellKnownOauthAuthorizationServerSplatRoute:
    DotwellKnownOauthAuthorizationServerSplatRoute,
  DotwellKnownOauthProtectedResourceSplatRoute:
    DotwellKnownOauthProtectedResourceSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMcpSplatRoute: ApiMcpSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1ModelsRoute: ApiV1ModelsRoute,
  DotwellKnownOauthAuthorizationServerIndexRoute:
    DotwellKnownOauthAuthorizationServerIndexRoute,
  DotwellKnownOauthProtectedResourceIndexRoute:
    DotwellKnownOauthProtectedResourceIndexRoute,
  ApiManifestIndexRoute: ApiManifestIndexRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
  ApiSetupStatusIndexRoute: ApiSetupStatusIndexRoute,
  ApiV1BrandsBrandIdRoute: ApiV1BrandsBrandIdRouteWithChildren,
  ApiV1CompetitorsCompetitorIdRoute: ApiV1CompetitorsCompetitorIdRoute,
  ApiV1OrganizationsOrganizationIdRoute:
    ApiV1OrganizationsOrganizationIdRouteWithChildren,
  ApiV1PromptsPromptIdRoute: ApiV1PromptsPromptIdRouteWithChildren,
  ApiV1ReportsReportIdRoute: ApiV1ReportsReportIdRoute,
  ApiV1ToolsAnalyzeRoute: ApiV1ToolsAnalyzeRoute,
  ApiPlausibleEventIndexRoute: ApiPlausibleEventIndexRoute,
  ApiV1BrandsIndexRoute: ApiV1BrandsIndexRoute,
  ApiV1CompetitorsIndexRoute: ApiV1CompetitorsIndexRoute,
  ApiV1DocsIndexRoute: ApiV1DocsIndexRoute,
  ApiV1OrganizationsIndexRoute: ApiV1OrganizationsIndexRoute,
  ApiV1PromptsIndexRoute: ApiV1PromptsIndexRoute,
  ApiV1ReportsIndexRoute: ApiV1ReportsIndexRoute,
  ApiPlausibleJsScriptIndexRoute: ApiPlausibleJsScriptIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
